<footer class="theme-footer-eight mt-100">
    <div class="top-footer">
        <div class="container">
            <div class="row ">
                <div class="col-xl-4 col-lg-3 col-12 footer-about-widget">
                    <div class="logo"><a href="<?php echo url()?>"><img src="<?php echo assetUrl('styles/main/')?>images/timably-logo-with-text.jpg" style="width: 200px" alt=""></a></div>
                    <ul class="font-rubik mt-10">
                        <li><a href="mailto:deskiinc@gmail.com">team@timably.com</a></li>
                        <li><a href="tel:+161 412 3224" class="phone">+161 412 3224</a></li>
                    </ul>
                </div> <!-- /.about-widget -->
                <div class="col-lg-3 col-md-4 footer-list justify-content-end">
                    <h5 class="footer-title">Links</h5>
                    <ul>

                        <li><a href="#pricing">Pricing</a></li>
                        <li><a href="<?php echo url('contact-us')?>">Contact us</a></li>

                    </ul>
                </div> <!-- /.footer-list -->


                <div class="col-lg-3 col-md-4 footer-list justify-content-end">
                    <h5 class="footer-title">Others</h5>
                    <ul>

                        <li><a href="<?php echo url('privacy')?>">Terms &amp; conditions</a></li>
                        <li><a href="<?php echo url('privacy')?>">Privacy policy</a></li>
                    </ul>
                </div> <!-- /.footer-list -->
            </div> <!-- /.row -->
        </div> <!-- /.container -->
    </div>

    <div class="container">
        <div class="bottom-footer mt-50 md-mt-30">
            <div class="row">
                <div class="col-lg-6 order-lg-2 mb-20">
                    <p class="copyright text-center text-lg-left">Copyright @<?php echo date('Y')?> Timaby inc.</p>
                </div>
                <div class="col-lg-6 order-lg-3 mb-20">
                    <ul class="d-flex justify-content-center justify-content-lg-end social-icon">
                        <li><a href="https://web.facebook.com/timably" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="httos://twitter.com/timably"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    </ul>
                </div>

            </div>
        </div>
    </div>
</footer> <!-- /.theme-footer-eight -->




<!-- Scroll Top Button -->
<button class="scroll-top">
    <i class="las la-angle-up"></i>
</button>