<div class="main-page-wrapper p0 font-gordita">
    <!-- ===================================================
        Loading Transition
    ==================================================== -->

    <!--
    =============================================
        Theme Main Menu
    ==============================================
    -->
    <?php echo view('home/menu')?>


    <?php echo view('home/menu')?>

</div>