<div class="content-top">
    <?php echo view('posts/menu')?>
</div>
<?php $page = $C->request->segment(2, 'running')?>
<div class="pane-container">
    <div class="pane-head clearfix" style="padding: 1px 20px">
        <div class="float-left">
            <a href="<?php echo url('publishing/parties')?>" data-ajax="true" class="btn shadow-none <?php echo ($page == 'running') ? 'btn-light':null?> " style="margin-top: 8px"><?php _l('running')?></a>
            <a href="<?php echo url('publishing/parties/templates')?>" data-ajax="true" class="btn shadow-none <?php echo ($page == 'templates') ? 'btn-light':null?>" style="margin-top: 8px"><?php _l('templates')?></a>
            <a href="<?php echo url('publishing/parties/shared')?>" data-ajax="true" class="btn shadow-none <?php echo ($page == 'shared') ? 'btn-light':null?>" style="margin-top: 8px"><?php _l('shared')?></a>


        </div>

        <div class="float-right">
            <a href=" " onclick="return Timably.openPane('#new-party-modal')" class="btn btn-light mt-2"><?php _l('start-a-party')?></a>
        </div>
    </div>
    <div class="content-scroller " data-height="90">

        <div class="modern-table">
            <?php if($parties->results()):?>
            <div class="table-head clearfix" style="margin-top: 10px;padding:0 20px">
                <div class="each" style="width: 30%;">
                    <?php _l('party-name')?>
                </div>

                <div class="each" style="width: 30%;">
                    <?php _l('statistics')?>
                </div>
                <div class="each" style="width: 10%;">
                    <?php _l('posts')?>
                </div>
                <div class="each" style="width: 10%;">
                    <?php _l('created-on')?>
                </div>
                <div class="each" style="width: 20%;">
                    <span class="float-right"><?php _l('actions')?></span>
                </div>
            </div>
            <?php endif?>

            <div class="table-body">

                <?php if($parties->results()):?>
                    <?php foreach($parties->results() as $party):?>
                        <div class="table-row clearfix shadow-0" style="padding:5px 20px">


                            <div class="each clearfix" style="width: 30%;">
                                <div class="left">
                                    <?php _l('party-name')?>
                                </div>
                                <div class="right">

                                    <a data-ajax="true" href="<?php echo url('publishing/party/'.$party['unique_key'])?>"><h5><span style="width:20px;height:20px;background:<?php echo ($party['color']) ? $party['color']: '#000'?>;display: inline-block;position: relative;top: 5px;margin-right: 7px"></span> <?php echo $party['title']?></h5></a>
                                </div>
                            </div>
                            <div class="each clearfix" style="width: 30%;">
                                <div class="left">
                                    <?php _l('statistics')?>
                                </div>
                                <div class="right">
                                    <a data-ajax="true" href="<?php echo url('publishing/party/'.$party['unique_key'])?>" class="btn btn-light shadow-none mb-1">
                                        <?php _l('published')?> <span class="badge badge-primary"><?php echo model('party')->countPartyPosts($party['id'], 1)?></span>
                                    </a>
                                    <a data-ajax="true" href="<?php echo url('publishing/party/'.$party['unique_key'])?>" class="btn btn-light shadow-none">
                                        <?php _l('pending')?> <span class="badge badge-dark"><?php echo model('party')->countPartyPosts($party['id'], 0)?></span>
                                    </a>
                                </div>

                            </div>
                            <div class="each clearfix" style="width: 10%;">
                                <div class="left">
                                    <?php _l('posts')?>
                                </div>
                                <div class="right">
                                    <span class="badge badge-light" style="font-size: 20px"><?php echo model('party')->countPartyPosts($party['id'])?></span>
                                </div>
                            </div>
                            <div class="each clearfix" style="width: 10%;">
                                <div class="left">
                                    <?php _l('created')?>
                                </div>
                                <div class="right">
                                    <span class="badge badge-light" style="font-size: 13px;margin-top: 7px"><?php echo date('m/d/Y h:iA', $party['created_at'])?></span>
                                </div>
                            </div>

                            <div class="each clearfix" style="width: 20%;">
                                <div class="left">
                                    <?php _l('actions')?>
                                </div>
                                <div class="right">
                                    <div class=" float-right" role="group" aria-label="Button group with nested dropdown">
                                        <span> <?php echo ($party['status']) ? '<span class="badge badge-success">'.l('running').'</span>' : '<span class="badge badge-dark">'.l('not-running').'</span>'?></span>

                                        <?php if($party['status'] == 1):?>
                                            <a style="min-width: auto" href="<?php echo url('publishing/party/'.$party['unique_key'])?>?action=status&status=0" class="btn btn-outline-danger btn-sm confirm shadow-none mtitle" title="<?php _l('stop-posting')?>" data-ajax-action="true"><i class="las la-stop-circle"></i></a>
                                        <?php elseif($party['status'] == 0):?>
                                            <a style="min-width: auto" href="<?php echo url('publishing/party/'.$party['unique_key'])?>?action=status&status=1" class="btn btn-outline-primary btn-sm confirm shadow-none mtitle" title="<?php _l('start-posting')?>" data-ajax-action="true"><i class="las la-play-circle"></i></a>
                                        <?php endif?>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="modal  modal-right" tabindex="-1" id="templateEditModal<?php echo $party['id']?>" role="dialog">
                            <div class="modal-dialog" role="document">
                                <form action="<?php echo getFullUrl(true)?>" method="post" class="general-form short-form">
                                    <input type="hidden" name="val[action]" value="edit"/>
                                    <input type="hidden" name="val[id]" value="<?php echo $party['id']?>"/>
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title"><?php _l('edit-template')?></h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <input type="hidden" name="val[create]" value="1"/>
                                            <div class="form-group ">
                                                <label><?php _l('template-name')?></label>
                                                <input type="text" class="form-control" value="<?php echo $party['title']?>" name="val[title]"/>
                                            </div>
                                            <div class="form-group mt-5">
                                                <label><?php _l('choose-color')?></label>

                                                <div class="btn-group-toggle folder-color-chooser" data-toggle="buttons">
                                                    <?php $i=0; foreach(model('file')->getFolderColors() as $color):?>
                                                        <label class="btn btn-secondary btn-float <?php echo ($color == $party['color']) ? 'active':null?> btn-sm shadow-none" style="background-color:<?php echo $color?>">
                                                            <input type="radio" name="val[color]" <?php echo ($color == $party['color']) ? 'checked':null?> id="option<?php echo $i?>" autocomplete="off" value="<?php echo $color?>">
                                                        </label>
                                                        <?php $i++; endforeach;?>


                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php _l('cancel')?></button>
                                            <button type="submit" class="btn btn-primary" style="color: #ffffff;"><?php _l('save')?></button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    <?php endforeach?>
                <?php else:?>
                    <div class="empty-result">
                        <img style="max-width:40%;margin: 10px 0;margin-bottom: 30px " src="<?php echo assetUrl('styles/main/images/planned-post-welcome.webp')?>"/>

                        <h5><?php _l('no-party-started-added-yet')?> </h5>
                    </div>
                <?php endif?>
            </div>
        </div>
    </div>
</div>
