<div class="content-top">
    <?php echo view('posts/menu')?>
</div>
<div class="pane-container">

    <div class="pane-left">
        <div class="pane-head">
            <h5 class="truncate" style="padding:15px 20px;width: 90%"><?php echo $party['title']?></h5>

            <a href="" data-toggle="modal" data-target="#partySettingsModal" style="position:absolute;right: 10px;top:20px;font-size:20px;"><i class="las la-cog"></i></a>
        </div>

        <div class="statistics-container">
            <div class="stats-container" style="padding: 10px ;margin: 0">
                <div class="each clearfix">
                    <div class="float-left">
                        <i class="las la-calendar-check"></i>
                        <h6><?php _l('published')?></h6>
                    </div>
                    <div class="float-right">
                        <div class="count"><?php echo model('party')->countPartyPosts($party['id'], 1)?></div>
                    </div>
                </div>
                <div class="each clearfix bg-lightblue mt-2">
                    <div class="float-left">
                        <i class="las la-calendar-minus"></i>
                        <h6><?php _l('pending')?></h6>
                    </div>
                    <div class="float-right">
                        <div class="count"><?php echo model('party')->countPartyPosts($party['id'], 0)?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-3 p-2">
            <h5><?php _l('posting-to')?>:</h5>
            <?php $accounts = perfectUnserialize($party['account'])?>
            <?php foreach($accounts as $account):$account = model('social')->find($account)?>
                <div class="each-posting-to-account">
                    <div class="avatar" style="background-image:url(<?php echo assetUrl($account['avatar'])?>)"></div>
                    <div class="title">
                        <h6 class="truncate"><?php echo $account['username']?></h6>
                    </div>
                </div>
            <?php endforeach?>
        </div>
    </div>
    <div class="pane-right">
        <div class="pane-head clearfix">
            <div class="float-left">
                <a href="" class="btn btn-light shadow-none" data-toggle="dropdown"><i class="las la-plus"></i> <?php _l('add-post')?></a>
                <div class="dropdown-menu">
                    <a href="" class="dropdown-item" onclick="return PartyTemplate.addMedia(0)"><?php _l('add-single-media')?></a>
                    <a href="" class="dropdown-item" onclick="return PartyTemplate.addMedia(1)"><?php _l('add-multi-media')?></a>
                    <a href="" class="dropdown-item" onclick="return PartyTemplate.openAddText()"><?php _l('add-text')?></a>

                </div>
                <?php echo ($party['status']) ? '<span class="badge badge-success">'.l('running').'</span>' : '<span class="badge badge-secondary">'.l('not-running').'</span>'?></span>

            </div>
            <div class="float-right dropdown  pr-2">


                <?php if($party['status']):?>
                    <a href="<?php echo getFullUrl()?>?action=status&status=0" class="btn btn-danger confirm" data-ajax-action="true"><?php _l('stop-posting')?></a>
                <?php else:?>
                    <a href="<?php echo getFullUrl()?>?action=status&status=1" class="btn btn-light confirm" data-ajax-action="true"><?php _l('start-posting')?></a>
                <?php endif?>
                <span class="dropdown">
                <a href="" class="btn btn-light " data-toggle="dropdown" style="min-width: auto"><i class="las la-ellipsis-v"></i></a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a href="" class="dropdown-item" data-title="<?php echo $party['title']?>" onclick="return PartyTemplate.openNewTemplate(this,null, '<?php echo $party['id']?>')">Save as template</a>
                    <a  style="min-width: auto" href="<?php echo getFullUrl()?>?action=delete-party" class="dropdown-item confirm " data-ajax-action="true" ><?php _l('delete-party')?></a>

                </div>
            </span>

            </div>
        </div>
        <div class="content-scroller" data-height="130">

            <div class="party-posts-list parties-posts-list">
                <?php if($posts):?>
                    <div class="alert alert-info">
                        <strong>Please Note:</strong> The post are arrange in the order of the date and time selected,you can also drag and re-arrange but make sure the date and time are in order
                    </div>
                <?php endif?>
                <?php foreach($posts as $post):?>
                    <?php echo view('parties/display-post', array('post' => $post))?>
                <?php endforeach;?>
            </div>
            <?php if(!$posts):?>
                <div class="empty-result">
                    <img style="max-width:70%;margin: 0px 0;margin-bottom: 30px " src="<?php echo assetUrl('styles/main/images/empty.png')?>"/>

                    <h5><?php _l('no-template-posts-added-yet')?> </h5>
                    <a href=""  class="btn btn-sm btn-primary shadow-none" onclick="return PartyTemplate.addMedia(0)" ><?php _l('add-first-post')?></a>
                </div>
            <?php endif?>
        </div>
    </div>
</div>

<div class="modal" id="addTextModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><?php _l('add-text')?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div style="position:relative;">
                    <textarea  class="form-control emoji-text" placeholder="<?php _l('editor-placeholder')?>"  id="add-text-modal" name="val[content]"></textarea>
                    <a href="" class="mtitle" title="<?php _l('choose-saved-captions')?>" data-type="captions" data-editor="#add-text-modal" onclick="return loadTemplates(this)" style="position:absolute;right: 5px;top: 30px;font-size:20px;color:grey"><i class="icons icon-layers"></i></a>
                    <a href="" class="mtitle" title="<?php _l('choose-saved-hashtags')?>" data-type="hashtag" data-editor="#add-text-modal" onclick="return loadTemplates(this)" style="position:absolute;right: 5px;top: 60px;font-size:20px;color:grey"><i class="las la-hashtag"></i></a>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php _l('cancel')?></button>
                <button type="button" class="btn btn-primary" onclick="return PartyTemplate.addText()"><?php _l('add')?></button>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="partySettingsModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><?php _l('party-settings')?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="<?php echo getFullUrl()?>" method="post" class="general-form">
                <input type="hidden" name="val[action]" value="update-settings"/>
                <div class="modal-body">
                    <div class="new-party-forms">
                        <div class="form-group ">
                            <label for="exampleInputEmail1"><?php _l('party-title')?></label>
                            <input type="text" name="val[title]" value="<?php echo $party['title']?>" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" >
                        </div>
                    </div>

                    <div class="form-group ">
                        <label><?php _l('start-date')?></label>
                        <input type="text" name="val[date]" value="<?php echo date('m/d/Y', $party['start_date'])?>" class="form-control datepicker-input"/>
                    </div>

                    <div class="form-group">
                        <label><?php _l('timezone')?></label>
                        <?php $user = model('user')->authUser?>
                        <select class="form-control select-timezone" name="val[timezone]">
                            <option value=""><?php _l('select-timezone')?></option>
                            <?php foreach(getTimezones() as $key => $name):?>
                                <option <?php echo $party['timezone'] == $key ? 'selected' : null?> value="<?php echo $key?>"><?php echo $name?></option>
                            <?php endforeach?>
                        </select>
                    </div>
                    <div class="form-group mt-5">
                        <label><?php _l('choose-color')?></label>

                        <div class="btn-group-toggle folder-color-chooser" data-toggle="buttons">
                            <?php $i=0; foreach(model('file')->getFolderColors() as $color):?>
                                <label class="btn btn-secondary btn-float <?php echo ($color == $party['color']) ? 'active':null?>  btn-sm shadow-none" style="background-color:<?php echo $color?>">
                                    <input type="radio" name="val[color]" <?php echo ($color == $party['color']) ? 'checked':null?>  id="option<?php echo $i?>" autocomplete="off" value="<?php echo $color?>">
                                </label>

                                <?php $i++; endforeach;?>


                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php _l('close')?></button>
                    <button type="submit" class="btn btn-primary"><?php _l('save') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>