<h1>Total Users - <?php echo count($users)?></h1>


<table style="width: 100%">
    <thead>
        <tr>
            <th style="width: 30%">Name</th>
            <th style="width:50%">Email address</th>
            <th style="width:20%">Plan</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($users as $user):?>
            <tr style=" border-top: solid 1px grey">
                <td style="width: 30%"><?php echo $user['name']?></td>
                <td style="width: 50%"><?php echo $user['email']?></td>
                <td style="width: 20%"><?php echo ($user['type'] == 1) ? 'Party' : 'Do More'?></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>