<?php echo view('templates/top', array('active' => 'captions'))?>
<div class="content-body">
    <div class="row">
        <div class="col-md-10">
            <div class="content-scroller modern-scroll">
                <div class="modern-table">
                    <div class="table-head clearfix">
                        <div class="each" style="width: 30%;">
                            <?php _l('template-name')?>
                        </div>
                        <div class="each" style="width: 50%;">
                            <?php _l('template-content')?>
                        </div>
                        <div class="each" style="width: 20%;">
                            <span class="float-right"><?php _l('template-actions')?></span>
                        </div>
                    </div>

                    <hr/>

                    <?php
                    autoLoadVendor();
                    $emojione = new \Emojione\Client(new \Emojione\Ruleset());
                    ?>

                    <div class="table-body" >
                        <?php foreach($captions as $caption):?>
                            <div class="table-row clearfix shadow-0">


                                <div class="each clearfix" style="width: 30%;">
                                    <div class="left">
                                        <?php _l('template-name')?>
                                    </div>
                                    <div class="right">
                                        <?php echo $caption['title']?>
                                    </div>
                                </div>
                                <div class="each clearfix" style="width: 50%;">
                                    <div class="left">
                                        <?php _l('template-content')?>
                                    </div>
                                    <div class="right">
                                        <?php echo  $emojione->shortnameToImage($caption['caption'])?>
                                    </div>
                                </div>

                                <div class="each clearfix" style="width: 20%;">
                                    <div class="left">
                                        <?php _l('template-actions')?>
                                    </div>
                                    <div class="right">
                                        <div class="btn-group float-right" role="group" aria-label="Button group with nested dropdown">
                                            <a href="" data-toggle="modal" data-target="#captionEditModal<?php echo $caption['id']?>" class="btn btn-light btn-sm"><i class="la la-pencil-alt"></i></a>
                                            <a href="<?php echo url('captions', array('action' => 'delete', 'id' => $caption['id']))?>"  class="btn btn-light btn-sm confirm" data-ajax-action="true" data-message="<?php _l('caption-delete-confirm')?>"><i class="las la-trash-alt"></i></a>

                                        </div>
                                        <div class="modal  modal-right" tabindex="-1" id="captionEditModal<?php echo $caption['id']?>" role="dialog">
                                            <div class="modal-dialog" role="document">
                                                <form action="<?php echo getFullUrl(true)?>" method="post" class="general-form short-form">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title"><?php _l('edit-template')?></h5>
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <input type="hidden" name="val[edit]" value="<?php echo $caption['id']?>"/>
                                                            <div class="form-group ">
                                                                <label><?php _l('template-name')?></label>
                                                                <input type="text" class="form-control" value="<?php echo $caption['title']?>" name="val[title]"/>
                                                            </div>

                                                            <div class="form-group mt-5">
                                                                <label><?php _l('template-content')?></label>
                                                                <div class="text-editor-placeholder">
                                                                    <div class="holder" contenteditable="true" >
                                                                        <img class="img-button" style="top: 5px;height:23px" src="<?php echo assetUrl('assets/images/emoji-text.png')?>"/>
                                                                        <?php echo  $emojione->shortnameToImage($caption['caption'])?>
                                                                    </div>
                                                                    <textarea   name="val[content]"   class="  form-control"  ><?php echo  $emojione->shortnameToUnicode($caption['caption'])?></textarea>

                                                                </div>
                                                            </div>

                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php _l('cancel')?></button>
                                                            <button type="submit" class="btn btn-primary" style="color: #ffffff;"><?php _l('save')?></button>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="side-help">
                <h3><?php _l('how-to-use-captions')?></h3>
                <p>
                    <?php _l('how-to-use-captions-note')?>
                </p>
            </div>
        </div>
    </div>
</div>

<a href="" class="btn btn-primary floating-button  btn-float" data-toggle="modal" data-target="#addTemplateModal"><i class="las la-plus"></i></a>

<div class="modal  modal-right" tabindex="-1" id="addTemplateModal" role="dialog">
    <div class="modal-dialog" role="document">
        <form action="<?php echo getFullUrl(true)?>" method="post" class="general-form short-form">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"><?php _l('add-template')?></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="val[create]" value="1"/>
                    <div class="form-group floating-label">
                        <label><?php _l('template-name')?></label>
                        <input type="text" class="form-control" name="val[title]"/>
                    </div>

                    <div class="form-group mt-5">
                        <label><?php _l('template-content')?></label>
                        <textarea class="form-control emoji-text" name="val[content]"></textarea>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php _l('cancel')?></button>
                    <button type="submit" class="btn btn-primary" style="color: #ffffff;"><?php _l('create-template')?></button>
                </div>
            </div>
        </form>
    </div>
</div>