<div data-type="image"  class="each-container sort each-file-drag fc-event " data-raw="<?php echo $graphic['file_url']?>" data-id="<?php echo $graphic['id']?>" data-file="<?php echo assetUrl($graphic['file_url'])?>">
    <div onclick="selectThisFile(this)" class="each shadow-1 each-file each-file-<?php echo $graphic['id']?> <?php echo (isset($selected) and $selected) ? 'selected' : null?>"
         style="background-image: <?php echo 'url('.assetUrl($graphic['file_url']).')'?>;"
         data-raw="<?php echo $graphic['file_url']?>"
         data-id="<?php echo $graphic['id']?>"
         data-thumbnail="<?php echo assetUrl($graphic['file_url'])?>"
         data-file="<?php echo assetUrl($graphic['file_url'])?>" data-type="image">
        <input type="hidden" value="<?php echo $graphic['id']?>" name="val[files][]"/>

        <div class="the-content">
            <div class="clearfix">
                <div class="float-left dropdown">
                    <a href=""  onclick="return previewFile(this,'<?php echo assetUrl($graphic['file_url'])?>','<?php echo 'image'?>')" class="btn btn-light menu" ><i class="las la-eye"></i></a>
                    <a href="" class="btn btn-light menu"><i class="icons icon-paper-plane"></i></a>
                </div>
                <div class="float-right">
                    <div class="custom-control custom-checkbox">
                        <input onchange="selectThisFile(this)" data-id="<?php echo $graphic['id']?>" type="checkbox" class="custom-control-input" id="customCheck<?php echo $graphic['id']?>"  value="<?php echo $graphic['id']?>" name="val[files][]">
                        <label class="custom-control-label" for="customCheck<?php echo $graphic['id']?>"></label>
                    </div>
                </div>
            </div>
            <a href="" onclick="return PhotoEditor.open(1000,1000, '<?php echo urlencode(assetUrl($graphic['file_id']))?>')" class="btn btn-primary edit-btn mtitle" title="<?php _l('use-template')?>"><i class="las la-pen"></i></a>


        </div>
    </div>
</div>
