<?php echo view('files/menu')?>
<?php
$selectedMain = $C->request->segment(1);
$mainCategoryId = $C->request->segment(1);
$mainCategory = model('admin')->getGraphicCategory($mainCategoryId);
$subCategoryId = $C->request->segment(2);
$subCategory = ($subCategoryId) ? model('admin')->getGraphicCategory($subCategoryId) : null
?>
<div class="pane-container graphics-page">
    <div class="pane-left" >
        <div class="side-collections-container mt-3" style="display: block">

            <div class="collection-list">
                <a data-ajax="true" href="<?php echo url('graphics')?>" class="each each-collection <?php echo (!$mainCategoryId) ? 'active':null?>">
                    <span class="line"></span>
                    <i style="color:  #703CD8 !important" class="icons color icon-folder-alt" ></i>
                    <span class="text" style="font-weight: bold">New Graphics</span>
                </a>
                <?php $month = model('admin')->getMonthGraphicCategory()?>
                <?php if($month):?>
                    <a data-ajax="true" href="<?php echo url('graphics/'.$month['id'])?>" class="each each-collection <?php echo ($mainCategoryId == $month['id']) ? 'active':null?>">
                        <span class="line"></span>
                        <i style="color:  #FF5722 !important" class="icons color icon-folder-alt" ></i>
                        <span class="text" style="font-weight: bold;color:#000"><?php echo $month['title']?></span>
                    </a>
                <?php endif?>
                <?php foreach(model('admin')->getGraphicCategories() as $category):?>
                    <a data-ajax="true" href="<?php echo url('graphics/'.$category['id'])?>" class="each each-collection <?php echo ($mainCategoryId == $category['id']) ? 'active':null?>">
                        <span class="line"></span>
                        <i style="color:  <?php echo $category['color']?> !important" class="icons color icon-folder-alt"></i>
                        <span class="text"><?php echo $category['title']?></span>
                    </a>
                    <div class="collection-list" style="margin-left: 15px;display: <?php echo ($mainCategoryId == $category['id']) ? 'block':'none'?>">
                        <?php foreach(model('admin')->getGraphicCategories($category['id']) as $category):?>
                            <a href="<?php echo url('graphics/'.$mainCategoryId.'/'.$category['id'])?>" data-ajax="true" class="each each-collection <?php echo ($subCategoryId == $category['id']) ? 'active':null?> ">
                                <span class="line"></span>
                                <i style="color:  <?php echo $category['color']?> !important" class="icons color icon-folder-alt"></i>
                                <span class="text"><?php echo $category['title']?></span>
                                <span class="count"><?php echo model('admin')->countCategoryGraphics($category['id'])?></span>
                            </a>
                        <?php endforeach;?>
                    </div>

                <?php endforeach;?>

            </div>
        </div>
    </div>
    <div class="pane-right">
        <?php if($term = $C->request->input('term')):?>
            <div class="pane-head">
                <div class="float-left">
                    <h5 class="mt-1">Showing result for : <?php echo $term?></h5>
                </div>
                <div class="float-right ">
                    <a href="" class="btn  btn-light shadow-none select-button" onclick="return selectAllFiles(this)"><i class="las la-check"></i> <?php _l('mark-all')?></a>
                    <a href="" class="btn  btn-light shadow-none deselect-button hide" onclick="return deselectAllFiles(this)"><i class="las la-check"></i> <?php _l('unmark-all')?></a>
                    <span class="dropdown">
                        <a href="" style="min-width: auto" class="btn btn-light shadow-none" data-toggle="dropdown"><i class="las la-adjust"></i></a>
                        <div class="dropdown-menu static-dropdown-menu dropdown-menu-right" style="width: 250px">
                            <h5 style="margin: 10px 15px">Filter by Color</h5>
                            <div class="graphic-page-url hide"><?php echo getFullUrl()?></div>
                            <div class="filter-color clearfix" style="padding-left: 15px">
                                <?php $colors = explode(',', $C->request->input('colors'));?>
                                <?php foreach(model('admin')->getCategoryColors($mainCategoryId) as $color):?>
                                    <a href="" onclick="return Filemanager.checkColors(this)" data-color="<?php echo str_replace('#', '', $color['color'])?>"  class="each <?php echo (in_array(str_replace('#', '', $color['color']), $colors)) ? 'active':null?>" style="background-color:<?php echo $color['color']?>">
                                    </a>
                                <?php endforeach;?>
                            </div>
                        </div>
                    </span>
                    <span class="dropdown">
                        <a href="" data-toggle="dropdown" class="btn btn-light  shadow-none" style="padding:11px !important;min-width: auto"><i class="las la-ellipsis-v"></i></a>
                        <div class="dropdown-menu dropdown-menu-right" style="width: 250px">
                            <a href="" onclick="return Filemanager.startParty()"  class="dropdown-item"><?php _l('start-a-party')?></a>
                            <a href="" onclick="return Filemanager.scheduleMultiPhoto()" class="dropdown-item"><?php _l('schedule-mult-photo')?></a>
                            <a href="" onclick="return Filemanager.createTemplate()" class="dropdown-item"><?php _l('create-template')?></a>
                            <a href="" class="dropdown-item  " onclick="return Filemanager.copy()"   style="padding:11px !important;min-width: auto"><?php _l('copy-graphics')?></a>
                        </div>
                    </span>
                </div>
            </div>
            <div class="content-scroller" data-height="115">
                <div class="content-body">
                    <div class="files-list files-grid">
                        <?php $graphics = model('admin')->getGraphics(null,$C->request->input('colors'),$C->request->input('styles'), ($selectedMain) ? null : 50, $term);?>

                        <?php foreach($graphics as $graphic):?>
                            <?php echo view('files/graphics/display', array('graphic' => $graphic))?>
                        <?php endforeach;?>
                        <?php echo view('files/filler')?>
                    </div>
                </div>
            </div>
        <?php else:?>
            <div class="pane-head">
                <div class="float-left">
                    <?php if($selectedMain):?>
                        <?php if($subCategoryId):?>
                            <h5 class="mt-1"><?php echo $subCategory['title']?></h5>
                        <?php else:?>
                            <h5 class="mt-1"><?php echo $mainCategory['title']?></h5>
                        <?php endif?>
                    <?php else:?>
                        <h5 class="mt-1"><?php _l('new-design-template')?></h5>
                    <?php endif?>

                </div>
                <div class="float-right ">
                    <a href="" class="btn  btn-light shadow-none select-button" onclick="return selectAllFiles(this)"><i class="las la-check"></i> <?php _l('mark-all')?></a>
                    <a href="" class="btn  btn-light shadow-none deselect-button hide" onclick="return deselectAllFiles(this)"><i class="las la-check"></i> <?php _l('unmark-all')?></a>
                    <span class="dropdown">
                        <a href="" style="min-width: auto" class="btn btn-light shadow-none" data-toggle="dropdown"><i class="las la-adjust"></i></a>
                        <div class="dropdown-menu static-dropdown-menu dropdown-menu-right" style="width: 250px">
                            <h5 style="margin: 10px 15px">Filter by Color</h5>
                            <div class="graphic-page-url hide"><?php echo getFullUrl()?></div>
                            <div class="filter-color clearfix" style="padding-left: 15px">
                                <?php $colors = explode(',', $C->request->input('colors'));?>
                                <?php foreach(model('admin')->getCategoryColors($mainCategoryId) as $color):?>
                                    <a href="" onclick="return Filemanager.checkColors(this)" data-color="<?php echo str_replace('#', '', $color['color'])?>"  class="each <?php echo (in_array(str_replace('#', '', $color['color']), $colors)) ? 'active':null?>" style="background-color:<?php echo $color['color']?>">
                                    </a>
                                <?php endforeach;?>
                            </div>
                        </div>
                    </span>
                    <span class="dropdown">
                        <a href="" data-toggle="dropdown" class="btn btn-light shadow-none " style="min-width: auto"><i class="las la-filter"></i></a>
                        <div class="dropdown-menu static-dropdown-menu dropdown-menu-right" style="width: 250px;height: 400px;padding: 10px">
                            <h6 class="dropdown-header"><?php _l('filter-by-styles')?></h6>
                            <div class="" style="overflow: auto;overflow-x: hidden;height: 88%">
                                <?php $styles = explode(',', $C->request->input('styles'))?>
                                <?php foreach(model('admin')->getGraphicStyles() as $style):?>
                                    <div onclick="Filemanager.checkedStyles(this)" class="custom-control custom-checkbox">
                                      <input <?php echo (in_array($style, $styles)) ? 'checked':null?> type="checkbox" class="custom-control-input style-inputs" value="<?php echo $style?>" id="customCheckdss<?php echo $style?>">
                                      <label class="custom-control-label" for="customCheckdss<?php echo $style?>"><?php echo ucwords($style)?></label>
                                    </div>
                                <?php endforeach;?>
                            </div>

                        </div>
                    </span>
                    <span class="dropdown">
                        <a href="" data-toggle="dropdown" class="btn btn-light  shadow-1" style="padding:11px !important;min-width: auto"><i class="las la-ellipsis-v"></i></a>
                        <div class="dropdown-menu dropdown-menu-right" style="width: 250px">
                            <a href="" onclick="return Filemanager.startParty()"  class="dropdown-item"><?php _l('start-a-party')?></a>
                            <a href="" onclick="return Filemanager.scheduleMultiPhoto()" class="dropdown-item"><?php _l('schedule-mult-photo')?></a>
                            <a href="" onclick="return Filemanager.createTemplate()" class="dropdown-item"><?php _l('create-template')?></a>
                            <a href="" class="dropdown-item  " onclick="return Filemanager.copy()"   style="padding:11px !important;min-width: auto"><?php _l('copy-graphics')?></a>
                        </div>
                    </span>
                </div>
            </div>

                <div class="content-scroller" data-height="115">
                    <div class="content-body">
                        <div class="files-list files-grid">
                            <?php $graphics = model('admin')->getGraphics(($subCategoryId) ? $subCategoryId : 'main-'.$mainCategoryId,$C->request->input('colors'),$C->request->input('styles'));?>

                            <?php foreach($graphics as $graphic):?>
                                <?php echo view('files/graphics/display', array('graphic' => $graphic))?>
                            <?php endforeach;?>
                            <?php echo view('files/filler')?>
                        </div>
                    </div>
                </div>

        <?php endif?>

    </div>
</div>