<div class="header">
    <a class="logo" href="<?php echo url('publishing')?>" data-ajax="true">
        <img class="light-logo" src="<?php echo assetUrl(config('site_short_icon','assets/images/short-logo.png'))?>"/>
    </a>

    <ul class="left-nav">
        <li>
            <a href="<?php echo url('publishing')?>" data-ajax="true" class="<?php echo ($C->activeIconMenu == 'publishing') ? 'active':null?> ">Publish</a>
        </li>
        <li>
            <a href="" class="">Go Live</a>
        </li>
        <li class="dropdown">
            <a href="" class="" data-toggle="dropdown"><i class="icons icon-grid"></i></a>
            <div class="dropdown-menu">
                cjkdshj
            </div>
        </li>
        <li>
            <a href="<?php echo url('files')?>" data-ajax="true" class="<?php echo ($C->activeIconMenu == 'files') ? 'active':null?>">Media</a>

        </li>
        <li>
            <a href="<?php echo url('accounts')?>" data-ajax="true" class="<?php echo ($C->activeIconMenu == 'accounts') ? 'active':null?>">Social accounts</a>
        </li>

    </ul>

    <ul class="clearfix">

        <li >
            <a href="" class="notification-icon  mtitle" title="Notifications"><i class="las la-bell"></i></a>
        </li>
        <li class="workspace-link-container dropdown">
            <a href="<?php echo url('workspace')?>" data-ajax="true" class="workspace-link clearfix mtitle" title="<?php _l('workspace')?>"   >
                <span class="workspace-icon"><?php echo model('user')->extractLetters($C->workspace['title'])?></span>
                <span class="workspace-info">
                    <span><?php echo strtoupper(l('workspace'))?></span>
                    <span><?php echo $C->workspace['title']?></span>
                </span>
            </a>
        </li>

        <li>
            <a href="" class="notification-icon beamer-notification-btn hide"><i class="las la-flag"></i></a>
        </li>
        <li class="dropdown">
            <a href="<?php echo url('profile')?>" data-ajax="true"  class="account-menu"><img src="<?php echo model('user')->getAvatar()?>"/> </a>

        </li>
    </ul>
</div>