<div id="app-container" class="clearfix <?php echo (session_get('open_menu', 0) == 1) ? 'opened-menu' : null?>">

    <?php if($C->appSideLayout):?>
        <div class="inner-container clearfix">
            <div class="inner-left-pane modern-scroll">
                <?php echo view($C->appSideLayout)?>
            </div>
            <div class="inner-right-pane">
                <?php echo $content?>
            </div>

        </div>
    <?php else:?>
        <?php echo $content?>
    <?php endif?>
</div>