<div id="app-container" class="clearfix <?php echo (session_get('open_menu', 0) == 1) ? 'opened-menu' : null?>">
    <div class="menu-pane">
        <div class="icon-menus">
            <a class="logo" href="<?php echo url('dashboard')?>" data-ajax="true">
                <img class="light-logo" src="<?php echo assetUrl(config('site_short_icon','assets/images/short-logo.png'))?>"/>
                <img class="dark-logo" src="<?php echo assetUrl(config('site_short_icon_light','assets/images/short-logo.png'))?>"/>
            </a>

            <div class="menu-list-container">
                <ul class="dropright" style="display: none">
                    <li style="display:none"><a class="account-icon" aria-haspopup="true" aria-expanded="false" data-toggle="dropdown" href="">
                            <img src="<?php echo ($C->selectedAccount) ? assetUrl($C->selectedAccount['avatar']) : model('user')->getAvatar()?>"/>
                        </a>
                        <div class="dropdown-menu social-accounts-menu" >
                            <!-- Dropdown menu links -->
                            <?php foreach(model('social')->getAccounts() as $account):?>
                                <a data-ajax="true" href="<?php echo getFullUrl()?>?switch=<?php echo $account['username']?>"
                                   class="dropdown-item <?php echo ($C->selectedAccount['id'] == $account['id']) ? 'active' : null?>" type="button"><img class="round-img-sm" src="<?php echo assetUrl($account['avatar'])?>"/> <?php echo $account['username']?></a>
                            <?php endforeach;?>

                            <div class="dropdown-divider"></div>
                            <a href="<?php echo url('accounts')?>" class="dropdown-item" data-ajax="true"><?php _l('manage-accounts')?></a>
                        </div>
                    </li>
                    <li style="display:none"><a href="" data-toggle="modal" data-target="#addAccountModal" title="<?php _l('add-account')?>" class="btn btn-light btn-float shadow-none add-button mtitle-right"><i class="las la-plus"></i></a> </li>
                    <li><a href="<?php echo url('posts')?>" data-ajax="true" title="<?php _l('compose-new-post')?>" class="btn compose-menu btn-primary mtitle-right btn-float shadow-none add-button"><i class="las la-edit"></i></a> </li>
                </ul>

                <ul class="main">
                    <li><a href="<?php echo url('posts')?>" data-ajax="true" class="mtitle-right <?php echo ($C->activeIconMenu == 'posts') ? 'active':null?>" title="<?php _l('dashboard')?>">
                            <i class="icons icon-paper-plane"></i>
                            Publishing
                        </a></li>
                    <li><a href="<?php echo url('insights')?>" data-ajax="true" class="mtitle-right <?php echo ($C->activeIconMenu == 'insights') ? 'active':null?>" title="<?php _l('insights')?>">
                            <i class="icons icon-bubble"></i>
                            Conversation
                        </a></li>
                    <li><a href="<?php echo url('insights')?>" data-ajax="true" class="mtitle-right <?php echo ($C->activeIconMenu == 'insights') ? 'active':null?>" title="<?php _l('insights')?>">
                            <i class="icons icon-link"></i>
                            Linkin.Bio
                        </a></li>
                     <li><a href="<?php echo url('insights')?>" data-ajax="true" class="mtitle-right <?php echo ($C->activeIconMenu == 'insights') ? 'active':null?>" title="<?php _l('insights')?>">
                             <i class="icons icon-graph"></i>
                             Insights
                         </a></li>
                    <li><a href="<?php echo url('captions')?>" data-ajax="true" title="<?php _l('templates')?>" class=" mtitle-right <?php echo $C->activeIconMenu == 'captions' ? 'active':null?>">
                            <i class="icons icon-grid"></i>
                            Templates
                        </a> </li>
                    <li><a href="<?php echo url('files')?>" data-ajax="true" title="<?php _l('file-manager')?>" class=" mtitle-right <?php echo $C->activeIconMenu == 'files' ? 'active':null?>">
                            <i class="icons icon-folder"></i>
                            Media
                        </a> </li>

                </ul>

            </div>
        </div>

    </div>
    <div class="content-pane">

        <div class="header">
            <div class="user-accounts clearfix">
                <?php foreach(model('social')->getAccounts() as $account):?>
                    <a data-ajax="true" title="<?php echo $account['username']?>" href="<?php echo getFullUrl()?>?switch=<?php echo $account['username']?>"
                       class="mtitle <?php echo ($C->selectedAccount['id'] == $account['id']) ? 'active' : null?>" ><img class="round-img-sm" src="<?php echo assetUrl($account['avatar'])?>"/> </a>
                <?php endforeach;?>

                <a href="<?php echo url('accounts')?>" data-ajax="true"  class="add"><i class="icons icon-user-follow"></i></a>
            </div>
            <ul>
                <li class="dropdown">
                    <?php $languages = model('admin')->getLanguages()?>
                    <a  data-toggle="dropdown" id="change-language-selector" class=" padding-sm btn dropdown-toggle language-selector shadow-1" href="#" >
                        <img style="width:20px" src="<?php echo assetUrl('assets/images/flags/'.Translator::instance()->lang().'.png')?>"/>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <?php foreach ($languages as $language):?>
                            <a href="<?php echo url('change/language', array('id' => $language['id']))?>" class="dropdown-item"> <img style="width: 17px;" class="mr-1" src="<?php echo assetUrl('assets/images/flags/'.$language['id'].'.png')?>"/> <span class="pt-1"><?php echo $language['name']?></span></a>
                        <?php endforeach;?>
                    </div>
                </li>
                <li class="dropdown">
                    <a href="" data-toggle="dropdown" class="account-menu"><img src="<?php echo model('user')->getAvatar()?>"/> </a>
                    <div class="dropdown-menu dropdown-menu-right dropdow-menu-lg">
                        <a class="dropdown-item" data-ajax="true" href="<?php echo url('profile')?>"><?php _l('my-account')?></a>
                        <a class="dropdown-item" data-ajax="true" href="<?php echo url('accounts')?>"><?php _l('manage-accounts')?></a>
                        <?php if(model('user')->isAdmin()):?>
                            <a class="dropdown-item"  href="<?php echo url('admincp')?>"><?php _l('admin-panel')?></a>
                        <?php endif?>
                        <div class="dropdown-divider" ></div>
                        <a class="dropdown-item"  href="<?php echo url('logout')?>"><?php _l('logout')?></a>
                    </div>
                </li>
            </ul>
        </div>

        <?php echo $content?>

    </div>

</div>

<div class="modal  modal-right modal-right" tabindex="-1" id="addTemplatesModal" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content p-0">
            <img src="<?php echo assetUrl('assets/images/loader.gif')?>"/>
        </div>
    </div>
</div>

<div class="modal fade bd-example-modal-lg " id="fileManagerModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><i class="icons icon-folder-alt"></i> <?php _l('choose-media')?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" >
                <div id="choose-files-container" data-container="#choose-files-container" data-paginate="true" data-offset="0" data-url="<?php echo url('files/load')?>" class="files-grid clearfix content-scroller modern-scroll" data-height="50">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php _l('close')?></button>
                <button type="button" class="btn btn-primary color-white" onclick="return Filemanager.add()"><?php _l('add')?></button>
            </div>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" id="postPreviewModal" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="post-preview" >
                <div class="regular-instagram-post ">
                    <div class="card-header" style="text-align:center;border-bottom: solid 1px #F5F5F5;">
                        <img src="<?php echo assetUrl('assets/images/instagram-logo.png')?>"/>
                    </div>
                    <div class="instagram-post-header">
                        <div class="avatar"></div>
                        <div class="header-info">
                            <div></div>
                            <div></div>
                        </div>
                    </div>
                    <div class="instagram-post-content">

                    </div>
                    <div class="instagram-post-caption">
                        <div></div>
                        <div></div>
                    </div>
                </div>
                <div class="video-instagram-post hide">

                </div>
            </div>
        </div>
    </div>
</div>