<div id="app-container" class="clearfix <?php echo (session_get('open_menu', 0) == 1) ? 'opened-menu' : null?>">
    <div class="menu-pane">
        <div class="icon-menus">
            <a class="logo" href="<?php echo url('publishing')?>" data-ajax="true">
                <img class="light-logo" src="<?php echo assetUrl(config('site_short_icon','assets/images/short-logo.png'))?>"/>
                <img class="dark-logo" src="<?php echo assetUrl(config('site_short_icon_light','assets/images/short-logo.png'))?>"/>
            </a>

            <div class="menu-list-container">
                <ul class="dropright" >

                </ul>

                <ul class="main">

                    <li><a href="<?php echo url('home')?>" data-ajax="true" class=" <?php echo ($C->activeIconMenu == 'home') ? 'active':null?>" title="<?php _l('home')?>">
                            <i class="las la-home"></i>
                        </a></li>
                    <li><a href="<?php echo url('publishing')?>" data-ajax="true" class=" <?php echo ($C->activeIconMenu == 'publishing') ? 'active':null?>" title="<?php _l('publishing')?>">
                            <i class="icons icon-paper-plane"></i>

                        </a></li>
                    <li>
                        <a href="<?php echo url('files')?>" data-ajax="true"  class=" <?php echo ($C->activeIconMenu == 'media') ? 'active':null?>" >
                            <i class="las la-images"></i>
                        </a>

                    </li>


                </ul>

            </div>
        </div>

    </div>

    <div class="content-pane">

        <?php echo view('includes/app/header')?>

        <?php echo $content?>
        <?php echo view('posts/modal')?>
        <?php echo view('account/modal')?>
        <div class="photo-editor-container">
            <div class="editor">
            </div>
            <a href="" onclick="return PhotoEditor.close()" class="btn btn-light close-btn"><?php _l('close-editor')?></a>
        </div>


        <div class="quick-help-container">
            <a href="" class="close-btn" onclick="return Timably.closeHelp()"><i class="las la-times"></i></a>
            <h2>Quick Help</h2>
            <hr/>
            <div class="row">
                <div class="col-6" style="height: calc(100vh - 100px);overflow: auto">

                    <div class="search">
                        <input onkeyup="Timably.searchQuickHelp(this)" class="quick-help-search-input" type="text" placeholder="Search quick help ...."/>
                        <i class="las la-search"></i>
                    </div>

                    <ul class="quick-help-menu clearfix">
                        <li>
                            <a onclick="return Timably.loadQuickHelp('basic')" href="" class="basic-btn active">
                                <i class="las la-search"></i>
                                <span>Learn the Basics</span>
                            </a>
                        </li>
                        <li>
                            <a href="" onclick="return Timably.loadQuickHelp('goals')" class="goals-btn">
                                <i class="las la-search"></i>
                                <span>Reach Goals</span>
                            </a>
                        </li>
                    </ul>

                    <p>New to Timably? Learn the basics in few minutes</p>
                    <div class="help-lists">

                    </div>
                </div>
                <div class="col-4">
                    <img style="width: 100%;margin-top: 30px" src="<?php echo assetUrl('styles/main/images/content-curation.webp')?>"/>

                    <div class="" style="text-align: center">
                        <a href="" class="btn  shadow-none"><i class="lab la-facebook"></i> Join our Support Facebook Group</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<div class="modal" tabindex="-1" id="newFacebookAccountModal" role="dialog">
    <div class="modal-dialog modal-dialog-centered "  role="document">
        <div class="modal-content">

            <div class="modal-body">
                <div class="account-type-selector-container clearfix">
                    <div class="each">
                       <a href="<?php echo url('accounts/facebook?auth=1&type=page')?>" class="ajax-action">
                           <i class="las la-flag"></i>
                           <span><?php _l('add-facebook')?> <br/> <?php _l('pages')?></span>
                       </a>
                    </div>

                    <div class="each">
                        <a href="<?php echo url('accounts/facebook?auth=1&type=group')?>" class="ajax-action">
                            <i class="las la-user-friends"></i>
                            <span><?php _l('add-facebook')?><br/> <?php _l('groups')?></span>
                        </a>
                    </div>
                </div>

                <div style="text-align: center;padding: 10px">
                    <a href=""  data-dismiss="modal" aria-label="Close" style="color: grey" ><?php _l('go-back')?></a>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="modal" tabindex="-1" id="newInstagramAccountModal" role="dialog">
    <div class="modal-dialog modal-dialog-centered "  role="document">
        <div class="modal-content">

            <div class="modal-body">
                <p>
                    The Instagram Official API currently support only Instagram Business accounts that have been connected to a Facebook Page
                </p>

                <p>You can <a href="">read here</a> to learn how you can convert your Instagram personal accounts to a Business account</p>

                <p>Also you need to connect your Facebook Page to your Instagram Business account <a href="">read more here</a> </p>

                <a href="<?php echo url('accounts/facebook?auth=1&type=instagram')?>" class="btn btn-lg btn-primary btn-block mb-3 ajax-action"><?php _l('continue')?></a>
                <div style="text-align: center;padding: 10px">
                    <a href=""  data-dismiss="modal" aria-label="Close" style="color: grey" ><?php _l('go-back')?></a>
                </div>
            </div>

        </div>
    </div>
</div>
<?php echo view('files/modal')?>
<div class="modal fade" id="importImageModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle"><?php _l('import-image-via-url')?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group floating-label">
                    <label><?php _l('image-url')?></label>
                    <input type="text" class="form-control" id="import-image-input" />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php _l('cancel')?></button>
                <button type="button" onclick="return Filemanager.importImage()" class="btn btn-primary"><?php _l('import')?></button>
            </div>
        </div>
    </div>
</div>

<div class="modal  " tabindex="-1" id="upgradeModal" role="dialog">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content p-0">
            <div class="modal-body">
                <img src="<?php echo assetUrl('styles/main/images/upgrade.gif')?>"/>

                <div style="text-align: center;margin: 20px 0">
                    <a href="" class="btn btn-primary disabled"><?php _l('Feature Coming soon ')?></a>

                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal  " tabindex="-1" id="becomeModal" role="dialog">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content p-0">
            <div class="modal-body">
                <img src="<?php echo assetUrl('styles/main/images/upgrade.gif')?>"/>

                <div style="text-align: center;margin: 20px 0">
                    <a href="" data-toggle="modal" data-target="#choosePlanModal"  class="btn btn-primary"><?php _l('Become a member')?></a>

                </div>
            </div>
        </div>
    </div>
</div>



<div class="modal  " tabindex="-1" id="newWelcomeModal" role="dialog">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content p-0">
            <div class="modal-body">
                <iframe style="width: 100%" height="415" src="https://www.youtube.com/embed/5ISH7kMcEQM?controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>                <div style="text-align: center;margin: 20px 0">
                    <h2>
                        Welcome on board!, <br/>
                        <span style="font-size:18px !important;font-weight: lighter">
                            Let me show you a quick video about Timably features, interface to get you started quickly
                        </span>
                    </h2>
                    <a href="" onclick="return Timably.closeWelcome()" class="btn btn-primary">Yes, Thanks I have Watch it</a>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal  modal-right modal-right" tabindex="-1" id="addTemplatesModal" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content p-0">
            <img src="<?php echo assetUrl('assets/images/loader.gif')?>"/>
        </div>
    </div>
</div>

