<div class="each-container" >
    <div class="each " style="cursor: pointer" >
        <div class="media" onclick="return Socialpost.selectWorkspace(<?php echo $workspace['id']?>)">
            <div class="media-image">

            </div>
            <div class="media-body">
                <h4 class="media-title"><?php echo $workspace['title']?></h4>
                <div class="info">
                    <span><?php echo model('workspace')->countAccounts($workspace['id'])?></span> <?php _l('social-accounts')?>
                     | <span style="color:grey"><strong><?php echo model('workspace')->countUsers($workspace['id']) + 1?></strong> <?php _l('users')?></span>
                </div>
            </div>
        </div>
        <div class="foot clearfix">
            <div class="float-left">
                <?php $user = model('user')->getUser($workspace['userid'])?>
                <div class="user-avatar mtitle" title="<?php echo $user['full_name']?> <?php _l('workspace')?>" style="background-image:url(<?php echo model('user')->getAvatar($user)?>)"></div>
            </div>
            <div class="float-right">
                <?php if($workspace['id'] == $C->workspaceId):?>
                    <span class="badge badge-light">Selected</span>
                <?php else:?>
                    <span class="badge badge-secondary" onclick="return Socialpost.selectWorkspace(<?php echo $workspace['id']?>)">Switch</span>
                <?php endif?>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="workspaceModal<?php echo $workspace['id']?>" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content" >
            <div class="modal-headr pt-3">
                <div class="nav-tabs-scrollable">
                    <ul class="nav  nav-tabs justify-content-center" id="justifiedTab" role="tablist">
                        <li class="nav-item">
                            <a aria-controls="home" aria-selected="true" class="nav-link active"   id="settings-tab-<?php echo $workspace['id']?>" data-toggle="tab" href="#settings-<?php echo $workspace['id']?>" role="tab"><?php _l('settings')?></a>
                        </li>
                        <li class="nav-item">
                            <a aria-controls="home" aria-selected="true" class="nav-link "   id="users-tab-<?php echo $workspace['id']?>" data-toggle="tab" href="#users-<?php echo $workspace['id']?>" role="tab"><?php _l('users')?></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="settings-<?php echo $workspace['id']?>" role="tabpanel" aria-labelledby="home-tab">

                </div>
                <div class="tab-pane fade" id="users-<?php echo $workspace['id']?>" role="tabpanel" aria-labelledby="profile-tab">
                    <div class="modal-body" style="min-height: 450px">


                    </div>

                </div>
                <div class="tab-pane fade" id="timetable-<?php echo $workspace['id']?>" role="tabpanel" aria-labelledby="contact-tab">
                    <div class="modal-body">
                        <p>timetable.</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
                <div class="tab-pane fade" id="approvals-<?php echo $workspace['id']?>" role="tabpanel" aria-labelledby="contact-tab">
                    <div class="modal-body">
                        <p>Approvals.</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>