<div class="user-data-page clearfix d-lg-flex">
    <div class="illustration-wrapper d-flex align-items-center justify-content-between flex-column">
        <h3></h3>
        <div class="illustration-holder">
            <img src="<?php echo assetUrl('styles/main/images/assets/ils_08.svg')?>" alt="" class="illustration">
            <img src="<?php echo assetUrl('styles/main/images/assets/ils_08.1.svg')?>" alt="" class="shapes shape-one">
            <img src="<?php echo assetUrl('styles/main/images/assets/ils_08.2.svg')?>" alt="" class="shapes shape-two">
        </div>
    </div> <!-- /.illustration-wrapper -->

    <div class="form-wrapper">
        <div class="d-flex justify-content-between">
            <div class="logo"><a href="<?php echo url()?>"><img src="<?php echo url('styles/main/images/timably-logo.png')?>" alt="" style="width:150px"></a></div>
        </div>
        <form action="<?php echo getFullUrl()?>" method="post" class="user-data-form mt-40 md-mt-40 general-form">
            <input type="hidden" name="val[action]" value="join"/>
            <h2>Join Workspace</h2>
            <p class="header-info pt-30 pb-50">
                You have been invited to join <strong><?php echo $workspace['title']?></strong> workspace,
                Click the button to accept
            </p>


            <div class="row " style="margin-top: 30px !important;">
                <?php $realUser = model('user')->getUser($user['assign_userid']);?>
                <?php if(!$realUser['password']):?>
                    <div class="col-12">
                        <div class="input-group-meta mb-40 sm-mb-40">
                            <label>Choose a new password</label>
                            <input required style="font-size: 20px" name="val[password]" type="password" placeholder="">
                        </div>
                    </div>
                <?php endif?>
                <div class="col-12">
                    <button class="theme-btn-one mt-20 mb-50">Accept Invitation</button>
                </div>
            </div>
        </form>
    </div> <!-- /.form-wrapper -->
</div> <!-- /.user-data-page -->
