<div class="pane-container pane-container-sm" style="height: calc(100vh - 63px)">
    <?php $workspace = $C->workspace;?>
    <?php echo view('profile/menu')?>
    <div class="pane-right">

        <div class="content-top">
            <h3 class="mt-3"><?php _l('team-members')?></h3>
            <hr/>
        </div>

        <div class="page-padding row">
            <div class="col-7">
                <div class="" style="position:relative;">

                    <form action="" method="post" class="general-form">
                        <div class="clearfix">
                            <h6 class="float-left"><?php _l('manage-users')?></h6>
                            <button type="submit" class="btn  btn-sm float-right"><?php _l('add-new-user')?></button>
                        </div>
                        <input type="hidden" name="val[action]" value="invite-user"/>
                        <input type="hidden" name="val[id]" value="<?php echo $workspace['id']?>"/>
                        <div class="row">
                            <div class="col-6">
                                <input name="val[email]" type="text" class="form-control input" placeholder="<?php _l('email-address')?>"/>
                            </div>
                            <div class="col-6">
                                <input name="val[name]" type="text" class="form-control input" placeholder="<?php _l('full-name')?>"/>
                            </div>
                            <div class="col-6">
                                <label><?php _l('permission')?></label>
                                <select name="val[permission]" class="form-control">
                                    <option value="1"><?php _l('contributor')?></option>
                                    <option value="2"><?php _l('approver')?></option>
                                    <option value="3"><?php _l('writer')?></option>
                                    <option value="4"><?php _l('client')?></option>
                                </select>
                            </div>
                            <div class="col-6">
                                <label><?php _l('user-type')?></label>
                                <select class="form-control" name="val[type]">
                                    <option value="1"><?php _l('team')?></option>
                                    <option value="2"><?php _l('external')?></option>
                                </select>
                            </div>
                        </div>
                    </form>
                    <?php if(!model('user')->canDoTeam()):?>
                        <div class="" style="width: 100%;height: 100%;background: rgba(255,255,255,0.9);position: absolute;top: 0;text-align: center;padding: 20px 0">
                            <i style="font-size: 50px;display: block;margin-bottom: 10px" class="las la-lock"></i>
                            <span style="color: grey">You need to be on business plan to add more users</span>
                        </div>
                    <?php endif?>
                </div>

                <div class="modern-table mt-3">
                    <div class="table-body workspace-users-list-<?php echo $workspace['id']?>">
                        <?php echo view('workspace/member/display-owner')?>
                        <?php foreach(model('workspace')->getMembers($workspace['id']) as $user):?>
                            <?php echo view('workspace/member/display', array('user' => $user))?>
                        <?php endforeach;?>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>