<?php $page = $C->request->segment(0)?>
<div class="nav-tabs-scrollable">
    <ul class="nav  nav-tabs " id="justifiedTab" role="tablist">

        <li class="nav-item">
            <a  class="nav-link <?php echo ($page == 'captions')? 'active': null?>" data-ajax="true" href="<?php echo url('captions')?>"  ><?php _l('captions')?></a>
        </li>
        <li class="nav-item">
            <a  class="nav-link <?php echo ($page == 'hashtags')? 'active': null?>" data-ajax="true" href="<?php echo url('hashtags')?>"  ><?php _l('hashtags')?></a>
        </li>
        <li class="nav-item">
            <a  class="nav-link " data-ajax="true" href="<?php echo url('publishing/parties/templates')?>"  ><?php _l('party-templates')?></a>
        </li>

    </ul>
</div>