<?php
autoLoadVendor();
$emojione = new \JoyPixels\Client(new \JoyPixels\Ruleset());
$medias = perfectUnserialize($post['medias']);
$canEdit = (isset($canEdit)) ? $canEdit : true;
?>
<div class="card shadow-1 mb-2 each each-party-post-<?php echo $post['id']?>">
    <div class="day-container">
        <?php _l('day')?>
        <input <?php echo (!$canEdit) ? 'disabled':null?> onkeyup="PartyTemplate.updateDay(this, '<?php echo $post['id']?>')" type="text" name="val[day]" value="<?php echo $post['day_number']?>" class="form-control"/>
    </div>
    <div class="media-container media-container-<?php echo $post['id']?>">
        <?php echo view('templates/party/utils/template-medias', array('post' => $post))?>
    </div>
    <div class="info clearfix">
        <div class="float-left" style="width: 70%;padding: 20px">
            <div class="text-editor-placeholder" style="position:relative;">
                <div class="holder" contenteditable="true" >
                    <?php if(!$post['caption']):?>
                        <span style="position:absolute;top: 7px; left: 7px;color:lightgrey"><?php _l('editor-placeholder')?></span>

                    <?php endif?>
                    <img class="img-button" style="top: 5px;height:23px" src="<?php echo assetUrl('assets/images/emoji-text.png')?>"/>
                    <?php echo  format_output_text($emojione->shortnameToUnicode($post['caption']))?>
                </div>
                <textarea data-id="<?php echo $post['id']?>" data-keyup="PartyTemplate.keyupResult"  placeholder="<?php _l('editor-placeholder')?>"   name="val[content]" id="add-text-input-<?php echo $post['id']?>"   class="  form-control"  ><?php echo  $emojione->shortnameToUnicode($post['caption'])?></textarea>

                <?php if($canEdit):?>
                    <a href="" class="mtitle" title="<?php _l('choose-saved-captions')?>" data-type="captions" data-editor="#add-text-input-<?php echo $post['id']?>" onclick="return loadTemplates(this)" style="position:absolute;right: 30px;bottom: 5px;font-size:17px;color:lightgrey"><i class="icons icon-layers"></i></a>
                    <a href="" class="mtitle" title="<?php _l('choose-saved-hashtags')?>" data-type="hashtag" data-editor="#add-text-input-<?php echo $post['id']?>" onclick="return loadTemplates(this)" style="position:absolute;right: 10px;bottom: 5px;font-size:17px;color:lightgrey"><i class="las la-hashtag"></i></a>

                <?php endif?>
            </div>
        </div>
        <div class="float-right " style="padding: 20px 5px;width:30%">
            <div style="position:relative;">
                <span style="position:absolute;top: 10px"><?php _l('time')?>:</span>
                <input <?php echo (!$canEdit) ? 'disabled':null?> onchange="PartyTemplate.updateTime(this, '<?php echo $post['id']?>')" type="text" style="padding-left: 40px" value="<?php echo $post['schedule_time']?>"  class="input-timepicker form-control"/>
            </div>
            <div class="mt-2">
               <?php if($canEdit):?>
                   <a href="" onclick="return PartyTemplate.addMediaToPost('<?php echo $post['id']?>')" class="btn btn-light shadow-none" style="min-width: auto;padding:11px 6px"><i class="las la-image"></i> <?php _l('add-media')?></a>
                   <a href="<?php echo getFullUrl()?>?action=duplicate-post&id=<?php echo $post['id']?>" class="btn btn-light shadow-none ajax-action mtitle" title="<?php _l('duplicate-post')?>"  style="min-width: auto"><i class="las la-copy"></i></a>

               <?php endif?>
                <a href="" title="<?php _l('preview-post')?>" class="mtitle btn btn-light shadow-none mt-1" onclick="return PostEditor.preview('<?php echo implode(',', $medias)?>','', this)" style="min-width: auto"><i class="las la-eye"></i>
                    <span class="hide"><?php echo nl2br($emojione->shortnameToUnicode($post['caption']))?></span>
                </a>

                <?php if($canEdit):?>
                    <a href="" class="btn btn-light shadow-none mt-1" onclick="return PartyTemplate.removePost('<?php echo $post['id']?>')" style="min-width: auto"><i class="las la-trash-alt"></i></a>

                <?php endif?>
            </div>
        </div>
    </div>
</div>