<div class="each <?php echo ($user['party_permission']) ? 'admins' : 'read-only'?>">
    <div class="avatar" style="background-image:url(<?php echo model('user')->getAvatar($user)?>)"></div>
    <div class="info clearfix">
        <div class="float-left">
            <h6><?php echo $user['full_name']?></h6>
            <?php if(!$user['party_permission']):?>
                <a href="" onclick="return Parties.makeAdmin('<?php echo $user['shared_id']?>', 1)"><?php _l('make-admin')?></a>
            <?php else:?>
                <a href="" onclick="return Parties.makeAdmin('<?php echo $user['shared_id']?>', 0)"><?php _l('remove-admin')?></a>
            <?php endif?>
        </div>
        <div class="float-right">
            <div><span class="badge badge-dark"><?php echo ($user['party_permission']) ? l('admin') : l('read-only')?></span></div>
            <?php _l('joined')?>: <?php echo time_elapsed_string('@'.$user['joined'])?>
        </div>
    </div>
</div>