<div class="content-top">
    <?php echo view('posts/menu')?>
</div>
<?php $page = $C->request->segment(2, 'running')?>
<div class="pane-container">
    <div class="pane-head clearfix" style="padding: 1px 20px">
        <div class="float-left">
            <a href="<?php echo url('publishing/parties')?>" data-ajax="true" class="btn shadow-none <?php echo ($page == 'running') ? 'btn-light':null?> " style="margin-top: 8px"><?php _l('running')?></a>
            <a href="<?php echo url('publishing/parties/templates')?>" data-ajax="true" class="btn shadow-none <?php echo ($page == 'templates') ? 'btn-light':null?>" style="margin-top: 8px"><?php _l('templates')?></a>
            <a href="<?php echo url('publishing/parties/shared')?>" data-ajax="true" class="btn shadow-none <?php echo ($page == 'shared') ? 'btn-light':null?>" style="margin-top: 8px"><?php _l('shared')?></a>


        </div>

        <div class="float-right">
            <a href=""  data-toggle="modal" data-target="#addTemplateModal" class="btn btn-light shadow-none" style="margin-top: 12px"><i class="las la-plus"></i> <?php _l('add')?></a>

        </div>
    </div>
    <div class="content-scroller " data-height="90">
        <div class="modern-table">
            <div class="table-head clearfix" style="margin-top: 10px;padding:0 20px">
                <div class="each" style="width: 50%;">
                    <?php _l('template-name')?>
                </div>
                <div class="each" style="width: 15%;">
                    <?php _l('template-posts')?>
                </div>
                <div class="each" style="width: 15%;">
                    <?php _l('created-on')?>
                </div>
                <div class="each" style="width: 20%;">
                    <span class="float-right"><?php _l('template-actions')?></span>
                </div>
            </div>

            <div class="table-body">

                <?php if($parties->results()):?>
                    <?php foreach($parties->results() as $party):?>
                        <div class="table-row clearfix shadow-0" style="padding:5px 20px">


                            <div class="each clearfix" style="width: 50%;">
                                <div class="left">
                                    <?php _l('template-name')?>
                                </div>
                                <div class="right">

                                    <a data-ajax="true" href="<?php echo url('templates/'.$party['unique_key'])?>">
                                        <h5>
                                            <span style="width:20px;height:20px;background:<?php echo ($party['color']) ? $party['color']: '#000'?>;display: inline-block;position: relative;top: 5px;margin-right: 7px"></span>
                                            <?php echo $party['title']?>
                                            <?php if($pageType == 'shared'):$user = model('user')->getUser($party['userid'])?>
                                                <span style="color:grey;">By : <?php echo $user['full_name']?></span>
                                            <?php endif?>
                                        </h5>
                                    </a>

                                </div>
                            </div>
                            <div class="each clearfix" style="width: 15%;">
                                <div class="left">
                                    <?php _l('template-posts')?>
                                </div>
                                <div class="right">
                                    <span class="badge badge-light" style="font-size: 20px"><?php echo model('party')->countPosts($party['id'])?></span>
                                </div>
                            </div>
                            <div class="each clearfix" style="width: 15%;">
                                <div class="left">
                                    <?php _l('created')?>
                                </div>
                                <div class="right">
                                    <span class="badge badge-light" style="font-size: 15px"><?php echo date('m/d/Y h:iA', $party['created_at'])?></span>
                                </div>
                            </div>

                            <div class="each clearfix" style="width: 20%;">
                                <div class="left">
                                    <?php _l('template-actions')?>
                                </div>
                                <div class="right">
                                    <div class=" float-right" role="group" aria-label="Button group with nested dropdown">
                                        <?php if($pageType == 'templates'):?>
                                            <a href="" data-toggle="modal" style="min-width: auto" data-target="#templateEditModal<?php echo $party['id']?>" class="btn btn-light btn-sm shadow-none mtitle" title="<?php _l('edit-template')?>"><i class="la la-pencil-alt"></i></a>
                                            <a href="<?php echo url('templates/'.$party['unique_key'])?>?action=delete-party" class="btn btn-light mtitle shadow-none confirm " data-ajax-action="true" title="<?php _l('delete-template')?>" style="min-width: auto"><i class="las la-trash-alt"></i></a>

                                        <?php else:?>
                                            <a href="<?php echo url('templates/'.$party['unique_key'])?>" class="btn btn-light mtitle shadow-none " title="<?php _l('View template')?>" style="min-width: auto"><i class="las la-eye"></i></a>

                                        <?php endif?>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="modal  modal-right" tabindex="-1" id="templateEditModal<?php echo $party['id']?>" role="dialog">
                            <div class="modal-dialog" role="document">
                                <form action="<?php echo getFullUrl(true)?>" method="post" class="general-form short-form">
                                    <input type="hidden" name="val[action]" value="edit"/>
                                    <input type="hidden" name="val[id]" value="<?php echo $party['id']?>"/>
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title"><?php _l('edit-template')?></h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <input type="hidden" name="val[create]" value="1"/>
                                            <div class="form-group ">
                                                <label><?php _l('template-name')?></label>
                                                <input type="text" class="form-control" value="<?php echo $party['title']?>" name="val[title]"/>
                                            </div>
                                            <div class="form-group mt-5">
                                                <label><?php _l('choose-color')?></label>

                                                <div class="btn-group-toggle folder-color-chooser" data-toggle="buttons">
                                                    <?php $i=0; foreach(model('file')->getFolderColors() as $color):?>
                                                        <label class="btn btn-secondary btn-float <?php echo ($color == $party['color']) ? 'active':null?> btn-sm shadow-none" style="background-color:<?php echo $color?>">
                                                            <input type="radio" name="val[color]" <?php echo ($color == $party['color']) ? 'checked':null?> id="option<?php echo $i?>" autocomplete="off" value="<?php echo $color?>">
                                                        </label>
                                                        <?php $i++; endforeach;?>


                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php _l('cancel')?></button>
                                            <button type="submit" class="btn btn-primary" style="color: #ffffff;"><?php _l('save')?></button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    <?php endforeach?>
                <?php else:?>
                    <div class="empty-result">
                        <img style="max-width:70%;margin: 20px 0;margin-bottom: 30px " src="<?php echo assetUrl('styles/main/images/empty.png')?>"/>

                        <h5><?php _l('no-party-template-added-yet')?> </h5>
                        <a href="" data-toggle="modal" data-target="#addTemplateModal" class="btn btn-sm btn-primary shadow-none" ><?php _l('create-new-template')?></a>
                    </div>
                <?php endif?>
            </div>
        </div>
    </div>
</div>



