<div class="cover-pane-container"  id="new-party-modal">
    <div class="cover-pane">
        <div class="content-top" style="background:none;border-bottom: none">

            <div class="right-actions pt-2">
                <a href="" onclick="return PostEditor.close(this)" style="min-width: auto" class="btn btn-light post-editor-close-btn shadow-none"><i class="las la-times"></i></a>
            </div>
        </div>

        <form action="<?php echo url('publishing/parties')?>" method="post" class="general-form" id="partyEditorForm">
            <input type="hidden" name="val[action]" class="add"/>
            <div class="content-body  content-body-with-tabs pt-0 content-scroller" data-height="0" style="overflow: auto">

                <div class="party-form-container">
                    <div class="" style="width: 40%;margin: 50px auto;margin-top: 10px">
                        <div class="btn-group btn-group-toggle shadow-none" data-toggle="buttons">
                            <label class="btn btn-light active">
                                <input onchange="Parties.changeCreateFrom(this)" type="radio" value="1" name="val[type]" id="option1" autocomplete="off" checked> <?php _l('new')?>
                            </label>
                            <label class="btn btn-light ">
                                <input onchange="Parties.changeCreateFrom(this)" type="radio" value="2" name="val[type]" id="option2" autocomplete="off"> <?php _l('copy-from-template')?>
                            </label>

                        </div>
                    </div>

                    <div class="new-party-forms">
                        <div class="form-group floating-label">
                            <label for="exampleInputEmail1"><?php _l('title')?></label>
                            <input type="text" name="val[title]" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" >
                        </div>
                    </div>

                    <input type="hidden" name="val[medias]" class="party-media-inputs"/>

                    <div class="copy-party-forms hide">
                        <div class="form-group">

                            <div class="clearfix ">
                                <select name="val[template]" class="form-control " style="width:90%">
                                    <option value="0"><?php _l('choose-template')?></option>
                                    <?php foreach (model('party')->getAllTemplates() as $template):?>
                                        <option value="<?php echo $template['id']?>"><?php echo $template['title']?></option>
                                    <?php endforeach;?>
                                    <optgroup label="Shared Templates"></optgroup>
                                    <?php foreach (model('party')->getShareTemplates()->results() as $template):?>
                                        <option value="<?php echo $template['id']?>"><?php echo $template['title']?></option>
                                    <?php endforeach;?>
                                </select>
                                <a href="<?php echo url('templates')?>" data-ajax="true" class="btn btn-light float-right mtitle" title="<?php _l('create-manage-templates')?>" style="min-width: auto;position:relative;bottom: 30px"><i class="las la-pencil-alt"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="form-group party-account-selector">
                        <label style="font-size:16px;"><?php _l('choose-facebook-group')?></label>
                        <?php echo view('posts/account-picker', array('reload' => 0, 'noPreload' => true, 'container' => 'party-account-selector', 'type' => 'facebook', 'accountType' => 'group', 'postEditor' => true))?>
                    </div>
                    <div class="form-group mt-5">
                        <label><?php _l('choose-color')?></label>

                        <div class="btn-group-toggle folder-color-chooser" data-toggle="buttons">
                            <?php $i=0; foreach(model('file')->getFolderColors() as $color):?>
                                <label class="btn btn-secondary btn-float  btn-sm shadow-none" style="background-color:<?php echo $color?>">
                                    <input type="radio" name="val[color]"  id="option<?php echo $i?>" autocomplete="off" value="<?php echo $color?>">
                                </label>

                                <?php $i++; endforeach;?>


                        </div>
                    </div>
                    <div class="form-group floating-label">
                        <label><?php _l('start-date')?></label>
                        <input type="text" name="val[date]" class="form-control datepicker-input"/>
                    </div>

                    <div class="form-group">
                        <label><?php _l('timezone')?></label>
                        <?php $user = model('user')->authUser?>
                        <select class="form-control select-timezone" name="val[timezone]">
                            <option value=""><?php _l('select-timezone')?></option>
                            <?php foreach(getTimezones() as $key => $name):?>
                                <option <?php echo $user['timezone'] == $key ? 'selected' : null?> value="<?php echo $key?>"><?php echo $name?></option>
                            <?php endforeach?>
                        </select>
                    </div>

                    <div class="copy-party-forms hide">
                        <div class="form-group floating-label">
                            <label for="exampleInputEmail1"><?php _l('replace-host-with')?></label>
                            <input type="text" class="form-control"  name="val[replaces][host]" >
                        </div>
                        <div class="form-group floating-label">
                            <label for="exampleInputEmail1"><?php _l('replace-link-with')?></label>
                            <input type="text" class="form-control"  name="val[replaces][link]" >
                        </div>
                    </div>

                    <div class="mt-3">
                        <button type="submit" class="btn btn-primary"><?php _l('create')?></button>
                    </div>

                </div>


            </div>
        </form>
    </div>
</div>

<div class="modal  modal-right" tabindex="-1" id="addTemplateModal" role="dialog">
    <div class="modal-dialog" role="document">
        <form action="<?php echo url('publishing/parties/templates')?>" method="post" class="general-form short-form">
            <input type="hidden" name="val[action]" value="add"/>
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"><?php _l('New Template')?></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="val[create]" value="1"/>
                    <div class="form-group ">
                        <label><?php _l('template-name')?></label>
                        <input type="text" class="form-control new-template-title"  name="val[title]"/>
                        <input type="hidden" name="val[medias]" class="party-media-inputs"/>
                        <input type="hidden" name="val[template_id]" class="new-template-template-id"/>
                        <input type="hidden" name="val[party_id]" class="new-template-party-id"/>
                    </div>
                    <div class="form-group mt-5">
                        <label><?php _l('choose-color')?></label>

                        <div class="btn-group-toggle folder-color-chooser" data-toggle="buttons">
                            <?php $i=0; foreach(model('file')->getFolderColors() as $color):?>
                                <label class="btn btn-secondary btn-float  btn-sm shadow-none" style="background-color:<?php echo $color?>">
                                    <input type="radio" name="val[color]"  id="option<?php echo $i?>" autocomplete="off" value="<?php echo $color?>">
                                </label>

                                <?php $i++; endforeach;?>


                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php _l('cancel')?></button>
                    <button type="submit" class="btn btn-primary" style="color: #ffffff;"><?php _l('submit')?></button>
                </div>
            </div>
        </form>
    </div>
</div>