<div class="main-page-wrapper  font-gordita">
    <!-- ===================================================
        Loading Transition
    ==================================================== -->

    <!--
    =============================================
        Theme Main Menu
    ==============================================
    -->
    <?php echo view('home/menu-page')?>
    <div class="fancy-hero-one">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 m-auto">
                    <h2 class="font-rubik">Help & Support</h2>
                    <p class="sub-heading">Trainings from our expert and proffessional Team</p>
                </div>
            </div>
            <form action="<?php echo url('helps')?>" class="search-form" method="get">
                <input type="text" name="term" value="" data-auto="false" placeholder="Search for help...">
                <button><img src="<?php echo assetUrl('styles/main/images/icon/47.svg')?>" alt=""></button>
            </form>
        </div>
        <div class="bubble-one"></div>
        <div class="bubble-two"></div>
        <div class="bubble-three"></div>
        <div class="bubble-four"></div>
        <div class="bubble-five"></div>
        <div class="bubble-six"></div>
    </div>

    <div class="faqs-inner-page">
        <img src="<?php echo assetUrl('styles/main/images/shape/66.svg')?>" alt="" class="shapes shape-one">
        <div class="shapes shape-two"></div>
        <div class="shapes shape-three"></div>
        <div class="shapes shape-four"></div>
        <div class="container">
            <div class="row">
                <div class="col-xl-11 m-auto">
                    <div class="all-faqs">
                        <div class="faqs-all-qus md-m0">
                            <div class="article-preview">
                                <div class="d-flex">
                                    <img src="<?php echo assetUrl($help['banner'])?>" alt="" class="avatar-img">
                                    <div>
                                        <h3 class="font-rubik"><?php echo $help['title']?></h3>
                                        <div class="avatar-info">
                                            Created on: <?php echo date('d M, Y', $help['created_at'])?>
                                        </div>
                                    </div>
                                </div>

                                <div class="article-details">
                                    <?php if($help['video_link']):?>
                                        <iframe style="width:100%" height="470" src="<?php echo $help['video_link']?>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                    <?php else:?>
                                        <div  class="help-banner" style="background-image:url(<?php echo assetUrl($help['banner'])?>);background-position:center;background-size:cover;width:100%;height:470px"></div>
                                    <?php endif?>
                                    <p style="font-size:20px !important;">
                                        <?php echo $help['content']?>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php echo view('home/footer')?>
</div>