<div class="main-page-wrapper  font-gordita">

    <?php echo view('home/menu-page')?>
    <div class="fancy-hero-one">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 col-lg-11 m-auto">
                    <div class="page-title">Contact us</div>
                    <h2 class="font-rubik">Feel free to contact us or just say hi!</h2>
                </div>
            </div>
        </div>
        <div class="bubble-one"></div>
        <div class="bubble-two"></div>
        <div class="bubble-three"></div>
        <div class="bubble-four"></div>
        <div class="bubble-five"></div>
        <div class="bubble-six"></div>
    </div>

    <div class="contact-us-light pt-140 pb-200 md-pt-90 md-pb-80">
        <div class="bubble-one"></div>
        <div class="bubble-two"></div>
        <div class="bubble-three"></div>
        <div class="bubble-four"></div>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-4 col-sm-6">
                    <div class="address-info">
                        <div class="icon"><img src="<?php echo assetUrl('styles/main/images/icon/15.svg')?>" alt=""></div>
                        <div class="title">Location</div>
                        <p class="font-rubik">Chicago <br> United States</p>
                    </div> <!-- /.address-info -->
                </div>
                <div class="col-md-4 col-sm-6">
                    <div class="address-info">
                        <div class="icon"><img src="<?php echo assetUrl('styles/main/images/icon/16.svg')?>" alt=""></div>
                        <div class="title">Contact</div>
                        <p class="font-rubik">team@timably.com </p>
                    </div> <!-- /.address-info -->
                </div>
                <div class="col-md-4 col-sm-6">
                    <div class="address-info">
                        <div class="icon"><img src="<?php echo assetUrl('styles/main/images/icon/17.svg')?>" alt=""></div>
                        <div class="title">Social Media</div>
                        <p class="font-rubik">Follow on social media</p>
                        <ul class="d-flex justify-content-center">
                            <li><a href="https://web.facebook.com/timably"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="httos://twitter.com/timably_"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>

                        </ul>
                    </div> <!-- /.address-info -->
                </div>
            </div>

            <div class="form-style-light">
                <form action="" class="general-form" id="contact-form" data-toggle="validator">
                    <div class="messages"></div>
                    <div class="row controls">
                        <div class="col-md-6">
                            <div class="input-group-meta form-group mb-35">
                                <label>First Name</label>
                                <input type="text" placeholder="Michel" name="val[firstname]" required="required" data-error="Name is required.">
                                <span class="placeholder_icon valid-sign"><img src="<?php echo assetUrl('styles/main/images/icon/18.svg')?>" alt=""></span>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="input-group-meta form-group mb-35">
                                <label>Last Name</label>
                                <input type="text" placeholder="Simon" name="val[lastname]" required="required" data-error="Name is required.">
                                <span class="placeholder_icon valid-sign"><img src="<?php echo assetUrl('styles/main/images/icon/18.svg')?>" alt=""></span>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="input-group-meta form-group mb-35">
                                <label>Your Email</label>
                                <input type="email" placeholder="gobapubo@gmail.com" name="val[email]" required="required" data-error="Valid email is required.">
                                <span class="placeholder_icon valid-sign"><img src="<?php echo assetUrl('styles/main/images/icon/18.svg')?>" alt=""></span>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="input-group-meta form-group lg mb-35">
                                <label>Your Message</label>
                                <textarea placeholder="Write your message here..." name="val[message]" required="required" data-error="Please,leave us a message."></textarea>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                        <div class="col-12"><button class="theme-btn-one ">Send Message</button></div>
                    </div>
                </form>
            </div> <!-- /.form-style-light -->
        </div>
    </div>
    <?php echo view('home/footer')?>
</div>
