<?php
$medias = perfectUnserialize($post['medias']);
?>
<?php if(count($medias) == 1):$media = $medias[0]?>
    <div class="single-media" style="background-image: <?php echo (isImage($media)) ? 'url('.assetUrl($media).')' : null?>">
        <?php if(!isImage($media)):?>
            <video src="<?php echo assetUrl($media)?>"/>
        <?php endif?>
        <input type="hidden" value="<?php echo $media?>" class="post-media-input"/>
        <a href="" data-id="<?php echo $post['id']?>" onclick="return PartyTemplate.removePostMedia(this, true)"><i class="las la-times"></i></a>
    </div>

<?php else:?>
    <?php foreach($medias as $media):?>
        <div class="each-media-container">
            <div class="each-media" style="background-image: <?php echo (isImage($media)) ? 'url('.assetUrl($media).')' : null?>">
                <?php if(!isImage($media)):?>
                    <video src="<?php echo assetUrl($media)?>"/>
                <?php endif?>
                <input type="hidden" value="<?php echo $media?>" class="post-media-input"/>
                <a data-id="<?php echo $post['id']?>" href="" onclick="return PartyTemplate.removePostMedia(this)"><i class="las la-times"></i></a>
            </div>
        </div>
    <?php endforeach?>
    <div  class="each-media-container filler"><div class="each-media"></div> </div>
    <div  class="each-media-container filler"><div class="each-media"></div> </div>
    <div  class="each-media-container filler"><div class="each-media"></div> </div>
    <div  class="each-media-container filler"><div class="each-media"></div> </div>
    <div  class="each-media-container filler"><div class="each-media"></div> </div>
    <div  class="each-media-container filler"><div class="each-media"></div> </div>
    <div  class="each-media-container filler"><div class="each-media"></div> </div>
    <div  class="each-media-container filler"><div class="each-media"></div> </div>
<?php endif?>