<div class="user-data-page clearfix d-lg-flex">
    <div class="illustration-wrapper d-flex align-items-center justify-content-between flex-column">
        <h3 class="font-rubik">Want to save huge  <br>time? <a href="<?php echo url('signup')?>">Sign up for account</a></h3>
        <div class="illustration-holder">
            <img src="<?php echo assetUrl('styles/main/images/assets/ils_08.svg')?>" alt="" class="illustration">
            <img src="<?php echo assetUrl('styles/main/images/assets/ils_08.1.svg')?>" alt="" class="shapes shape-one">
            <img src="<?php echo assetUrl('styles/main/images/assets/ils_08.2.svg')?>" alt="" class="shapes shape-two">
        </div>
    </div> <!-- /.illustration-wrapper -->

    <div class="form-wrapper">
        <div class="d-flex justify-content-between">
            <div class="logo"><a href="<?php echo url()?>"><img src="<?php echo url('styles/main/images/timably-logo.png')?>" alt="" style="width:150px"></a></div>

        </div>
        <form style="height: 70vh;overflow: auto" action="<?php echo getFullUrl()?>" method="post" class="user-data-form mt-40 md-mt-40 general-form">
            <h3>Timably Privacy Policy</h3>

            <p>
                Timably is committed to strong, transparent, and secure privacy practices.
                This policy explains what data we collect when you use timely platforms, services, products, and content. It also has information on how we store, transfer, use, and delete that information. Our motive supersedes complying with the privacy law but also at the same time earns your trust.
                The security and privacy of our customers and all individuals who use and visit timely are of utmost importance to us and we are devoted to protecting your Personal data. This policy applies to existing users and newly created accounts. Because we value your privacy and we aim for our
                services to be safe and enjoyable for everyone:
            </p>

            <p>
                -We will never sell your personal data to anyone.
                -We work strictly in compliance with European privacy laws.
                -You are in absolute control of your personal data at all times.
            </p>

            <h5>What information do we collect?</h5>
            Personal Information

            When you sign up for our service, you may provide us with some of your
            personal details that can be used to identify or contact you which includes your name, business name, email, and postal address.

            Account Information
            During sign up details and information about subscription plans, billing methods, and details about
            the usage of our services such as the information about users you invite, the information you provide when linking your social media
            accounts and any dates you schedule.

            <h5>-How do we use your information?</h5>
            Timably processes the personal information you provide for the purposes identified in this privacy policy page, with your consent of course, in compliance with a legal obligation to which timably is subject, for the conduct of contract to which you are a party. Timably uses the Personal Information collected from your sign-up and from your Facebook profile exclusively to provide you with the Services. We collect your Personal Information for the purpose of providing the Service, identifying and communicating with you, responding to your requests and inquiries, providing you with information on-boarding content, new features, and offers, improving our Services.
            We may combine the Personal Information we gather about you and the Log Data and Account information we collect automatically during your visit to our website. In doing so, it allows us to provide you with a unique and personalized experience that improves our Service.
            Furthermore, you may authorize Timably to access your accounts with some other additional social networking sites such as Linkedin, Twitter, or Instagram.
            In the case you choose to access these accounts, the said social networking site will provide Timably with its platform identification number for your
            profile, your profile image, profile name, and other profile details.
            Timably will only retain your personal data for as long as required to fulfill the purposes we collected it for, and also because of our
            lawful business interests that have been appraised and to satisfy any legal or reporting requirements.

            <h5>-Third-Party Data Processors and Service Providers</h5>

            When you are using our Services and have chosen to connect your Social Networks account to our Services, or if you authorize a Third-Party Service to
            access your account, you are agreeing to provide data about you to the Social Networks and the Third-Party Services under their respective privacy policies and terms.
            Please be aware that the third party services are not within our control. They are not covered by this Privacy Policy. In the case, you have any questions about Personal details you submit to these websites, you will be required to consult that site’s privacy policy.

            <h5>-How long do we retain your information?</h5>

            Our sole aim in Timably is to guard and assist you in areas of creation, management of your social media content, and these contents are saved as long as you maintain an account with Timably. Timably does not grant any third party access to or in any case release your content. We do not maintain or receive information as a result of
            your network posts, as regards information that may identify recipients of your posts.
            We retain your data as long as necessary to provide the Services requested by you, in compliance with our legal obligations, to resolve disputes, and to enforce the terms of the Services. After this, it is no longer required for us to retain details about you, or under other conditions upon your request, we will dispose of the information in a secure manner. You may delete your content at any time following the instructions on Timably. You may also cancel your account at any time.
            After which the Personal Information we saved and any other data will be wiped clean.

            <h5>-Security</h5>

            At Timably, the security of your Personal Information is important to us, and we aim to implement and maintain reasonable, acceptable security measures and practices that suits
            the nature of the information we save, in order to protect it from unauthorized access, use, modification, or disclosure.
            However, please be aware that no method of transmission over the internet is 100% and we are unable to guarantee the absolute and total security of the Personal Information we
            have collected from you.
            For any concerns and inquiries as regards our data security practices, please contact us as described in the Contact Us section below.

            <h5>-Cookies</h5>

            Just like many other sites, we collect certain information through the use of cookies, which are small text files that are stored by your browsers when you access our Site.
            We may use both session cookies and persistent cookies to identify that you’ve successfully logged in to our Site and to tells us when and how you connect with our Site.
            We may also use cookies to monitor web traffic routing on our Site and to customize and improve the Service we render to you.
            By visiting Timably or using the Service you agree to the use of cookies in your browser and HTML based emails.
            However, if you wish to delete or disable cookies, you may do so using your web browsers. It may be required for you to check with your provider to find out how to disable cookies nevertheless. Notwithstanding, as long a Cookies remain on your web browser, Timably can deliver faster service.

            <h5>-Notices and revision to the Privacy Policy</h5>

            In the case you have any concerns about your privacy, please kindly forward an email to Timably at team@timably.com containing a detailed description of your concerns.
            Timably will do its best to resolve such issues swiftly. We may revise our Privacy Policy from time to time.

            Consent

            By using our Services, or submitting personal information to Timably, or collecting personal data from Supported Platforms via the Service, you consent to the transfer,
            collection, storage disclosure, and use of your personal information in the way specified in this Privacy Policy. If you do not consent to the use of your personal information in these ways, you shall refrain from using the Service.

            <h5>-Children's Policy</h5>

            Our Service is not directed at persons under the age of thirteen (13), and we do not knowingly collect personally identifiable information from persons under the age of thirteen (13). Also, you must be over the minimum age to consent to the processing of your personal information as required by the laws of your jurisdiction to use our Service. Some countries in the European Union and elsewhere requires a minimum age of fourteen and above.
            In this event, you must be over the minimum age of consent where you reside. To gather this information, you must contact an appropriate website
            or qualified and experienced adult where you reside.

            -Data Processing by Timably

            If you reside in the European Economic Area or California and mainly use our Services to assist third parties with their social
            media schedule, you are categorized as a data controller (under GDPR) or business (under CCPA), and Timably acts as the data
            processor (under GDPR) or service provider (under CCPA) with respect to the personal data processed by us in connection with your use of
            the Services.

            <h5>Timably as a data controller</h5>

            Timably acts as a data controller when we are:

            Gathering details and data from you to set up your timetable account (account information such as your name and email address);
            Managing your social contacts and other related information to you;
            Oversee usage information on our site;
            Responding to support issues or general inquiries;


            <h5>-Your Rights Under the General Data Protection Regulation (GDPR)</h5>
            For your personal information, in accordance with certain, privacy laws, you have the following rights in respect to your Personal
            Information that we gather:
            1. Right of access. You have the absolute right at any time to ask us for a copy of the personal data about you that we hold.
            Where we have a good reason, and if the GDPR permits, we can refuse your request for a copy of your personally identifiable information, or certain elements of the request. In the case we refuse your request or any aspect of it, we will furnish you with our reasons for doing so.
            2. Right to rectification. The right to access rectification of your personal information in the case where the personally identifiable
            information provided is inaccurate or incomplete.
            3. Right of portability. In some specific instances, you have a right to receive any personally identifiable data that we hold about you.
            4. Right to deletion. The right to retrieve the deletion of your Personal data in certain circumstances, such as where the Personal
            data is no longer necessary in relation to the reasons for which it was saved.
            5. Right to object. The right to object, on issues relating to the processing of your Personal Information.
            If you desire to exert any of these rights, kindly submit your request here or contact us as provided in the Contact Us section below.
            Upon request, we will furnish you with information in the case we hold any of your personal information.

            <h5>-Contact Us</h5>

            If you have any questions about this Privacy Policy, please contact us at team@timably.com.








            <h4 id="terms">Terms of service</h4>


            <h6>Last modified: October 03, 2021</h6>

            Please review these Timably terms of service (“Terms of Service”) carefully. Timably (“Timably” or “we” or “us” or “our”) offers a software
            tool (“Service”) that helps businesses owners and agencies (individually and collectively “Customer(s)”) manage their social media profiles on
            Supported Platforms. By using the Service, you agree to be bound by these Terms of Service. If you do not accept these Terms of Service you shall not
            (and shall not have the right to) use the Service.
            The Software is the property of Timably and protected by trademark, copyright, and other intellectual property laws. Timably,
            along with its licensors, owns all rights, and interest in the Software, and reserves any rights not expressly granted in this Agreement.
            This Software may only be used for lawful purposes.

            The following terms apply to these Terms of Service:
            1.“Agreement” shall mean this User License Agreement – Terms of Service set on the Timably Site.
            2.“Account” shall mean the account created by this end-user. Each User must have an account and password.
            3.“Fees” shall mean the charges payable by each End-user.
            4." Services" or "Service" shall mean a mix of scheduling and social sharing services on offer through the Timably Site.
            5.“Subscription” shall mean the non-transferable, non-exclusive, right to use the Services, upon the creation of an Account, subject to the terms of this Agreement.

            Amendment

            We may review and change any part of this Agreement (along with any terms or documents integrated by reference in this Agreement) at any time by posting the amended terms on the Timably website. It is important from time to time for you to review this Agreement before using our Self-Serve Services. The amended Agreement will be active as of the time of posting, or on such later date as
            maybe specified in the updated Agreement, and will apply to your use of the Self-Serve Services from that moment.

            Assignment
            You may not commit your rights under this Agreement to anyone else. We may assign our rights to any other persons or entity.

            Payment Terms for Services
            The Fees for using the Services are posted on the Site and are contained in this Agreement. Timably has the right to change the Fees at any time and without sovereign notice to you. You must pay for the Services with either a valid credit/debit card acceptable to us,
            by another payment option that Timably may provide to you.
            By signing up for a subscription plan, the User agrees that his or her subscription will automatically be renewed upon completion of the subscription term. Unless the User cancels before the completion of the subscription term, User authorizes the Company to charge the payment card provided for the renewal term. The period of auto-renewal will be the same as the initial monthly or yearly subscription period unless contrarily stated
            to Owner, at the time the subscription was made.



            Owner's Cancellation of Services
            You may opt to cancel the Services at any time. To cancel the Services, navigate to your profile page found at https://timably.com/profile and follow the in prompts to cancel your auto-renewing subscription. On cancelation of the Services with Timably, you will not be charged again, but you are responsible for whatever charges that have already been incurred for the current monthly or annual billing period. The owner must cancel his or her subscription in conformity with the cancellation guidelines in Section 19(a) or as otherwise agreed in writing. The company will not refund fees
            that may have accrued to the Owner’s account and will not allow fees for a canceled subscription.



            Notices
            Timably may issue a notice to you by placing a banner notice on the Timably platform website. We may also contact you through your Timably account or contact information you provided, such as email or telephone. If you fail to provide accurate account information, such as contact information,
            you may not receive important information about our Self-Serve Services or this Agreement.



            Binding Contract
            This is a legally binding contract and all users agree to be bound by these terms and to also be liable to the company for any non-compliance with these terms.
            If any user does not agree to these terms, the user may not use the service.
            
           
        </form>
    </div> <!-- /.form-wrapper -->
</div> <!-- /.user-data-page -->
