<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="<?php echo output_content($description)?>">
    <meta name="keywords" content="<?php echo output_content($keywords)?>">
    <title><?php echo output_content($title)?></title>

    <link rel="apple-touch-icon" sizes="180x180" href="<?php echo output_content($favicon)?>">
    <link rel="shortcut icon" href="<?php echo output_content($favicon)?>">

    <link rel="apple-touch-icon-precomposed" href="<?php echo output_content($favicon)?>">
    <link rel="icon" href="<?php echo output_content($favicon)?>">
    <link href="<?php echo assetUrl('assets/css/plugin.css')?>?time=<?php echo fileatime(path('assets/css/plugin.css'))?>" rel="stylesheet">
    <link href="<?php echo assetUrl('assets/js/trumbowyg/ui/trumbowyg.min.css')?>" rel="stylesheet">

    <?php if($pageType == 'frontend'):?>
        <link href="<?php echo assetUrl('styles/main/css/style.css')?>?time=<?php echo fileatime(path('styles/main/css/style.css'))?>" rel="stylesheet">
    <?php elseif($pageType == 'admincp'):?>
        <link href="<?php echo assetUrl('styles/main/css/admincp.css')?>?time=<?php echo fileatime(path('styles/main/css/admincp.css'))?>" rel="stylesheet">
    <?php else:?>
        <link href="<?php echo assetUrl('styles/main/css/app.css')?>?time=<?php echo fileatime(path('styles/main/css/app.css'))?>" rel="stylesheet">
    <?php endif?>
    <?php echo $header_content?>
    <meta name="twitter:card" content="<?php echo config('site-title')?>" />
    <meta property="twitter:site" content="<?php echo url()?>">
    <meta property="og:site_name" content="<?php echo config('site-title')?>">

    <meta property="twitter:title" content="<?php echo config('site-title')?>">
    <meta property="twitter:description" content="<?php echo output_content($description)?>">
    <meta property="twitter:image" content="<?php echo assetUrl(config('site_logo', 'assets/images/logo.png'))?>">
    <meta property="og:url" content="<?php echo url()?>">
    <meta property="og:type" content="Website">
    <meta property="og:title" content="<?php echo config('site-title')?>">
    <meta property="og:description" content="<?php echo output_content($description)?>">
    <meta property="og:image" content="<?php echo assetUrl(config('site_logo', 'assets/images/logo.png'))?>">
    <?php Hook::getInstance()->fire("header.after.css")?>


    <?php if(config('google-analytics-id')):?>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=<?php echo config('google-analytics-id')?>"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', '<?php echo config('google-analytics-id')?>');
        </script>

    <?php endif?>



</head>

<body>
<div id="cover-loader"><img src="<?php echo assetUrl('styles/main/images/loader.gif')?>"/> </div>
<div id="top-loading"></div>
<div id="page-container">
    <?php echo $content?>


</div>

<div id="backtotop"><a href="#"></a></div>

<?php if(config('enable-gdpr', true)):?>
    <div class="gdpr-container" data-aos="fade-right" data-aos-duration="1000">
        <div><?php _l('gdpr-text')?></div>
        <div class="buttons mt-2">
            <a href="" onclick="return acceptCookie()" class="btn btn-primary"><?php _l('got-it')?></a>
        </div>
    </div>
<?php endif?>
<?php echo view('expired/modal')?>
</body>

<script>
    var baseUrl = '<?php echo url()?>';
    var permaLink = <?php echo config('permalink', false) ? 1 : 0?>;
    var isLoggedIn = <?php echo $C->model('user')->isLoggedIn() ? 'true' : 'false'?>;
    var strings = {
        are_your_sure: "<?php _l("are-you-sure")?>",
        yes: "<?php _l('yes')?>",
        cancel: "<?php _l('cancel')?>",
        ok : "<?php _l("ok")?>",
        close : "<?php _l("close")?>",
        notImageError : "<?php echo l("not-image-error")." : ". config("image-file-types", "jpg,png,gif,jpeg")?>",
        allowVideoSizeError : "<?php echo l("video-size-error")." : ". config("video-file-size", 55)?>MB",
        processing : "<?php _l("processing")?>",
        select_all : "<?php _l('select-all')?>",
        deselect : "<?php _l('deselect')?>",
        allowFileSizeError: "<?php _l('allow-upload-file-size-error')?> 20MB",
        notImageVideoError: "<?php _l('not-image-video-file-error')?>",
        challenge_required: "<?php _l('challenge_required')?>",
        verification_required: "<?php _l('verification-required')?>",
        add_account: "<?php _l('add-account')?>",
        select_an_account_to_continue: "<?php _l('select_an_account_to_continue')?>",
        please_select_image: "<?php _l('please_select_image')?>",
        please_select_video: "<?php _l('please_select_video')?>",
        please_select_story_error : '<?php _l('please_select_story_error')?>',
        please_select_live_video_error : '<?php _l('please_select_live_video_error')?>',
        please_select_igtv_error : '<?php _l('please_select_igtv_error')?>',
        please_select_live_video_error2: '<?php _l('please_select_live_video_error2')?>',
        please_select_igtv_error2: '<?php _l('please_select_igtv_error2')?>',
        please_select_one_account: '<?php _l('please_select_one_account')?>',
        need_edit_file_video: '<?php _l('need_edit_file_video')?>',
        select_account_actions: '<?php _l('you-need-select-account')?>',
        accounts_deleted: '<?php _l('accounts-deleted-success')?>',
        accounts_synced: '<?php _l('account_synced')?>',
        accounts_limit_reach: '<?php  _l('account-limit-reached')?>',
        accounts_connected_already: '<?php _l('account-connected-already')?>',
        choose_accounts: '<?php _l('choose-accounts')?>',
        sorting_error: "<?php _l('sorting-error')?>",
        add_text_content: "<?php _l('add-text-content-error')?>",
        confirm: "<?php _l('confirm')?>",
        pick_time: " <?php _l('pick-time')?>",
        label_title: "<?php _l('label-title')?>",
        label_add_error: "<?php _l('label_add_error')?>",
        share_link_copied: "<?php _l('share_link_copied')?>"

        <?php Hook::getInstance()->fire("js.translation")?>
    };
    var supportImagesType = "<?php echo config("image-file-types", "jpg,png,gif,jpeg")?>";
    var supportVideoType = "<?php echo (config('ffmpeg-path', '') == '') ? 'mp4' : 'mp4'?>";
    var allowPhotoSize = <?php echo 20 * 1024 * 1000?>;
    var allowFileSize = <?php echo 20 * 1024 * 1000?>;
    var lastTime = <?php echo time()?>;
    var siteTitle = "<?php echo config("site-title")?>";
    var logo = "<?php echo assetUrl(config('site_short_icon', 'assets/images/short-logo.png'))?>";
    var loaderImage = "<?php echo assetUrl('styles/main/images/loader.gif')?>";
    var stripeKey = "<?php echo config("stripe-publishable-key", "")?>";
    var enableWelcomeStemps = 0;
    var userId = '<?php echo model('user')->authOwnerId?>';
    var workspaceId = '<?php echo $C->workspaceId?>';
    var jwtAuth = '';
    <?php if(model('user')->isLoggedIn()): autoLoadVendor();?>
    jwtAuth = '<?php echo generateNoltToken(model('user')->authUser)?>';
    <?php endif?>
    <?php if($pageType != 'frontend'):?>
    var googleDriveDeveloperKey = "AIzaSyDMcM0oLJYcAURKF2V41mA_MGuXfGy-sT8";
    var googleDriveClientId = "648589569312-vgthib7pb7t0qm7kv18ctl47k38onc9u.apps.googleusercontent.com";
    var scope = ['https://www.googleapis.com/auth/drive.file'];
    var pickerApiLoaded = false;
    <?php endif?>

    <?php if($pageType != 'frontend'):?>
    // The Client ID obtained from the Google Developers Console. Replace with your own Client ID.

    var dateFormat = '<?php echo getAdminDateFormat(true)?>';
    var dateFormatId = '<?php echo getSelectedDateFormat()?>';
    var oauthToken;


    <?php endif?>
</script>
<script src="<?php echo assetUrl('assets/js/plugin.js')?>?time=<?php echo fileatime(path('assets/js/plugin.js'))?>"></script>
<script src="<?php echo assetUrl('assets/js/trumbowyg/trumbowyg.min.js')?>"></script>
<script src='https://cdn.tiny.cloud/1/4eudkp3t7ii81ucoc27v26luifagzk4swtmvwbx9mu5qvk4k/tinymce/5/tinymce.min.js' referrerpolicy="origin">
</script>
<script src="<?php echo assetUrl('styles/main/js/main.js')?>?time=<?php echo fileatime(path('styles/main/js/main.js'))?>"></script>
<?php Hook::getInstance()->fire("footer.after.js")?>

<?php if($pageType != 'frontend'):?>
    <script type="text/javascript" src="https://apis.google.com/js/api.js"></script>
    <script type="text/javascript" src="https://www.dropbox.com/static/api/2/dropins.js" id="dropboxjs" data-app-key="jpb4ltq4ft2xnvi"></script>


    <script>
        var beamer_config = {
            product_id : "womQbWun36859",
            button_position: 'top-right',
            selector: '.beamer-notification-btn'
        };
    </script>
    <script type="text/javascript" src="https://app.getbeamer.com/js/beamer-embed.js" defer="defer"></script>
    <script type="text/javascript">
        (function (document, url) {
            var script = document.createElement('script');
            script.src = url;
            script.onload = function () {
                // API initialization
                if (window.Canva && window.Canva.DesignButton) {

                    window.Canva.DesignButton.initialize({
                        apiKey: 'x9ZrDIhW73OSWzJXttEWdMVS',
                    }).then(function (api) {
                        window.canvaAPI = api;
                        //console.log(window.canvaAPI)
                    })

                }
            };
            document.body.appendChild(script);
        })(document, 'https://sdk.canva.com/designbutton/v2/api.js');
    </script>

<?php else:?>
    <script src="<?php echo assetUrl('styles/main/js/animate.js')?>"></script>
    <script>
        var  onloadCallback = function() {
            window.captchIsLoaded = true
        }
    </script>
    <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"
            async defer>
    </script>

<?php endif?>

<?php if($message = $C->request->input('message')):?>
    <script>
        $(function() {
            notify('<?php _l($message)?>', '<?php echo $C->request->input('type')?>');
        })
    </script>
<?php endif?>
<?php echo str_replace('&#39;', "'", config('embed-code', ''))?>
</body>
</html>