<div class="each-container ">
    <a
        <?php if(isset($load)):?>
            onclick="return Filemanager.openFolder('<?php echo url('files/load/'.$folder['id'])?>')"
            <?php elseif(isset($sideLoad)):?>
            onclick="return Filemanager.openSideFolder('<?php echo url('files/side/'.$folder['id'])?>')"

            <?php else:?>
            data-ajax="true"
            <?php endif?>
        href="<?php echo (isset($load)) ? 'javascript:void(0)' : url('files/'.$folder['id'])?>" class="each shadow-1 each-folder">
        <i class="icons icon-folder-alt" style="color: <?php echo $folder['folder_color'] ? $folder['folder_color'] : '#000'?> !important"></i>
        <h6><?php echo $folder['file_name']?></h6>
    </a>
</div>