<div class="content-top">
    <h3><?php _l('file-manager')?></h3>

</div>

<div class="content-body">
    <div class="row">
        <div class="col-md-10">
            <div class="clearfix mb-3">
                <div class="float-left">
                    <div class="" >
                        <button class="btn btn-sm btn-secondary active" data-toggle="modal" data-target="#addFolderModal"><i class="las la-folder-plus"></i> <?php _l('create-folder')?></button>
                        <?php if($C->request->segment(1)):$folder = model('file')->find($C->request->segment(1))?>
                            <a data-ajax-action="true" href="<?php echo url('files', array('action' => 'delete-folder','id' => $folder['id']))?>" class="confirm btn btn-sm btn-light mtitle shadow-1" style="min-width: 20px;" title="<?php _l('delete-folder')?>"><i class="las la-trash-alt"></i></a>
                            <button data-target="#editFolderModal" data-toggle="modal" class="btn btn-sm btn-light mtitle shadow-1" style="min-width: 20px;" title="<?php _l('edit-folder')?>"><i class="las la-pencil-alt"></i></button>

                            <div class="modal  modal-right" tabindex="-1" id="editFolderModal" role="dialog">
                                <div class="modal-dialog" role="document">
                                    <form action="<?php echo getFullUrl(true)?>" method="post" class="general-form short-form">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title"><?php _l('edit-folder')?></h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <input type="hidden" name="val[editfolder]" value="1"/>
                                                <input type="hidden" name="val[folder_id]" value="<?php echo $folder['id']?>"/>
                                                <div class="form-group  mt-4 has-data">
                                                    <label><?php _l('folder-title')?></label>
                                                    <input type="text" class="form-control" value="<?php echo $folder['file_name']?>" name="val[name]"/>
                                                </div>

                                                <div class="form-group mt-5">
                                                    <label><?php _l('folder-color')?></label>

                                                    <div class="btn-group-toggle folder-color-chooser" data-toggle="buttons">
                                                        <?php $i=0; foreach(model('file')->getFolderColors() as $color):?>
                                                            <label class="btn btn-secondary btn-float <?php echo ($color == $folder['folder_color']) ? 'active':null?> btn-sm shadow-none" style="background-color:<?php echo $color?>">
                                                                <input type="radio" name="val[color]" <?php echo ($color == $folder['folder_color']) ? 'checked':null?> id="option<?php echo $i?>" autocomplete="off" value="<?php echo $color?>">
                                                            </label>

                                                            <?php $i++; endforeach;?>


                                                    </div>
                                                </div>

                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php _l('cancel')?></button>
                                                <button type="submit" class="btn btn-primary" style="color: #ffffff;"><?php _l('submit')?></button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        <?php endif?>
                    </div>
                </div>
                <div class="float-right">
                    <div class="btn-group btn-group-toggle mr-4" >
                        <button onclick="return submitFilesForm()" class="btn btn-sm btn-light file-delete-button" disabled="disabled"><i class="las la-trash-alt"></i></button>
                        <button class="btn btn-sm btn-light select-button" onclick="return selectAllFiles(this)"><i class="las la-check-double"></i> <?php _l('select-all')?></button>
                        <button class="btn btn-sm btn-light hide deselect-button" onclick="return deselectAllFiles(this)"><i class="las la-check-double"></i> <?php _l('deselect-all')?></button>

                    </div>
                </div>
            </div>

            <div class="files-container scroll-paginate"
                 data-container="files-grid"
                 data-url="<?php echo getFullUrl()?>"
                 data-offset="0"
            >
                <div class="files-grid clearfix content-scroller modern-scroll" data-height="50">
                   <form id="files-form" action="" method="post" class="general-form">
                       <input type="hidden" name="val[action]" value="delete"/>
                       <?php if($C->request->segment(1)): ?>
                           <div class="each-container">
                               <a data-ajax="true" href="<?php echo ($folder['folder_id']) ? url('files/'.$folder['folder_id']) : url('files')?>" class="each each-back shadow-1">
                                   <i class="las la-arrow-left"></i>
                               </a>
                           </div>
                       <?php endif?>
                       <?php foreach(model('file')->getFolders($C->request->segment(1)) as $folder):?>
                           <?php echo view('files/folder', array('folder' => $folder));?>
                       <?php endforeach?>
                       <?php foreach($files as $file):?>
                           <?php echo view('files/display', array('file' => $file));?>
                       <?php endforeach?>
                   </form>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <h4><i class="las la-filter"></i> <?php _l('filter-media')?></h4>

            <div class="form-group">
                <select onchange="return filterMediaList(this)" class="form-control">
                    <option <?php echo ($C->request->input('type') == 'all') ? 'selected': null?> value="all"><?php _l('all-media')?></option>
                    <option <?php echo ($C->request->input('type') == 'image') ? 'selected': null?> value="image"><?php _l('image')?></option>
                    <option <?php echo ($C->request->input('type') == 'video') ? 'selected': null?> value="video"><?php _l('video')?></option>
                </select>
            </div>

            <div class="card mt-4 mb-4">
                <div class="card-body">
                    <h6 ><?php _l('usage')?></h6>

                    <div class="progress mb-2" style="height: 20px;">
                        <div class="progress-bar progress-purple"  role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <div class="clearfix">
                        <div class="float-right">
                            <strong>24MB / 100GB</strong>
                        </div>
                    </div>
                </div>
            </div>
            <div class="side-help">
                <h4 class="bold"><?php _l('how-to-use-file-manager')?></h4>
                <p>
                    <?php _l('how-to-use-file-manager-note')?>
                </p>
            </div>
        </div>
    </div>
</div>

<div class="floating-button dropdown  btn-float-dropdown">
    <button data-toggle="dropdown"  class="btn btn-float btn-primary shadow-24" type="button"><i style="font-size:20px" class="las la-cloud-upload-alt"></i></button>
    <div class="dropdown-menu">
        <button title="Upload from computer" class="btn btn-float btn-light btn-sm float-btn-text mtitle-left" type="button" style="position:relative;overflow: hidden">
            <i class="las la-desktop"></i>
            <form method="post"  data-upload="#upload-progress" action="<?php echo getFullUrl()?>" enctype="multipart/form-data" class="general-form filemanager-uploader">
                <input type="hidden" name="val[upload]" value="1"/>
                <input type="hidden" name="val[folder_id]" value="<?php echo $C->request->segment(1, 0)?>" class="file-folder-id-input"/>
                <input multiple onchange="validate_file_size(this, 'image-video','submit_file_upload')" type="file" name="file[]" style="position:absolute;top: 0;width: 100%;height: 100%;opacity: 0;z-index: 99;cursor: pointer">
                <i class="la la-plus"></i> <?php _l('upload')?>
            </form>
        </button>
        <button title="Upload from Dropbox" class="btn btn-float btn-light btn-sm float-btn-text mtitle-left" type="button"><i class="lab la-dropbox"></i></button>
        <button title="Upload from GoogleDrive" class="btn btn-float btn-light btn-sm float-btn-text mtitle-left" type="button"><i class="lab la-google-drive"></i></button>

    </div>
</div>

