<div class="content-top">

    <?php $page = $C->request->segment(0, 'files')?>
    <div class="nav-tabs-scrollable">
        <ul class="nav  nav-tabs " id="justifiedTab" role="tablist">
            <li class="nav-item">
                <a  class="nav-link <?php echo ($page == 'files')? 'active': null?>" data-ajax="true" href="<?php echo url('files')?>"  ><?php _l('my-library')?></a>
            </li>
            <li class="nav-item">
                <a  class="nav-link <?php echo ($page == 'graphics')? 'active': null?>" data-ajax="true" href="<?php echo url('graphics')?>"  >Content Library</a>
            </li>
        </ul>
    </div>
</div>