<form action="<?php echo getFullUrl()?>" method="post" class="user-data-form mt-40 md-mt-40 general-form">
    <h2>Reset Password</h2>
    <p class="header-info pt-30 pb-50">Still don't have an account? <a href="<?php echo url('signup')?>">Getstarted</a></p>
    <div class="alert alert-warning " style="display: none;margin-bottom: 15px" id="activationEmailSuccess">
        <strong><?php _l('email-sent-successful')?></strong><br/>
        <span><?php _l('reset-email-check')?></span>
    </div>
    <div class="row " style="margin-top: 30px !important;">

        <div class="col-12">
            <div class="input-group-meta mb-40 sm-mb-40">
                <label>Email</label>
                <input name="val[email]" type="email" placeholder="bolcovfed@ce.edu">
            </div>
        </div>

        <div class="col-12">
            <button class="theme-btn-one mt-20 mb-50">Submit</button>
        </div>
    </div>
</form>