<form action="<?php echo getFullUrl()?>" method="post" class="user-data-form mt-40 md-mt-40 general-form">
    <h2>Hi, welcome  Back!</h2>
    <p class="header-info pt-30 pb-50"></p>

    <div class="row">
        <div class="col-12">
            <div class="input-group-meta mb-40 sm-mb-40">
                <label>Email</label>
                <input name="val[email]" type="email" placeholder="bolcovfed@ce.edu">
            </div>
        </div>
        <div class="col-12">
            <div class="input-group-meta mb-15">
                <label>Password</label>
                <input name="val[password]" type="password" placeholder="Enter Password" class="pass_log_id">
                <span class="placeholder_icon"><span class="passVicon"><img src="<?php echo assetUrl('styles/main/images/icon/view.svg')?>" alt=""></span></span>
            </div>
        </div>
        <div class="col-12">
            <div class="agreement-checkbox d-flex justify-content-between align-items-center">
                <div style="opacity: 0">
                    <input type="checkbox" id="remember">
                    <label for="remember">Keep me logged in</label>
                </div>
                <a href="<?php echo url('forgot')?>">Forget Password?</a>
            </div> <!-- /.agreement-checkbox -->
        </div>
        <div class="col-12">
            <button class="theme-btn-one mt-10 mb-10">Login</button>
        </div>
        <div class="social-login-container">
            <h6>LOGIN WITH </h6>

            <a href="<?php echo url('facebook/auth')?>" class="facebook"><i class="lab la-facebook-f"></i></a>
            <a href="<?php echo url('twitter/auth')?>" class="twitter"><i class="lab la-twitter"></i></a>
            <a href="<?php echo url('google/auth')?>"  class="google"><i class="lab la-google"></i></a>
        </div>
    </div>
</form>