


<div class="welcome-title">
    <h3><?php _l('login')?></h3>
</div>

<form action="<?php echo getFullUrl(true)?>" method="post" class="general-form">

    <div class="form-group">
        <div class="floating-label">
            <label for="loginEmailAddress"><?php _l('email-address')?></label>
            <input aria-describedby="exampleFloatingLabel1Help" name="val[email]" class="form-control" id="loginEmailAddress" placeholder="<?php _l('email-address')?>" type="text">
        </div>
    </div>
    <div class="form-group">
        <div class="floating-label">
            <label for="loginPassword"><?php _l('password')?></label>
            <input aria-describedby="exampleFloatingLabel1Help" name="val[password]" class="form-control" id="loginPassword" placeholder="<?php _l('password')?>" type="password">
        </div>
    </div>


    <div  class="clearfix">
        <div class="float-left">

        </div>
        <div class="float-right">
            <a href="<?php echo url('forgot')?>" data-ajax="true" class="float-right mt-4 color-gr" ><?php _l('forgot-password')?>?</a>
        </div>
    </div>

    <button class="btn btn-block btn-raised btn-primary mt-3 btn-lg"><?php _l('login')?></button>
</form>


<?php if(config('user-signup', true) and !config('disable-landing', false)):?>
    <div class="clearfix mt-5">

        <a href="<?php echo url('signup')?>" data-ajax="true" class="color-grey font-bg mt-5"><?php _l('signup')?></a>
    </div>
<?php endif?>
