
<div class="welcome-title">
    <h3><?php _l('create-your-own-account')?></h3>
</div>

<form action="<?php echo getFullUrl(true)?>" method="post" class="general-form">
    <?php if(config('email-verification', false) or $C->request->input('message') == 'activate'):?>
        <div class="alert alert-warning " style="display: none;" id="activationEmailSuccess">
            <strong><?php _l('registeration-successful')?></strong><br/>
            <span><?php _l('activation-email-check')?></span>
        </div>
    <?php endif?>
    <div class="form-group">
        <div class="floating-label">
            <label  ><?php _l('full-name')?></label>
            <input type="password"  placeholder="<?php _l('full-name')?>" class="form-control" name="val[full_name]" >
        </div>
    </div>
    <div class="form-group">
        <div class="floating-label">
            <label  ><?php _l('email-address')?></label>
            <input type="password"  placeholder="<?php _l('email-address')?>" class="form-control" name="val[email]" >
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <div class="floating-label">
                    <label  ><?php _l('password')?></label>
                    <input type="password"  placeholder="<?php _l('password')?>" class="form-control" name="val[password]" >
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                <div class="floating-label">
                    <label  ><?php _l('confirm-password')?></label>
                    <input type="password" id="confirm" placeholder="<?php _l('confirm-password')?>" class="form-control" name="val[confirm]" >
                </div>

            </div>
        </div>
    </div>

    <?php Hook::getInstance()->fire('signup.extend')?>

    <select class="form-control select-timezone" name="val[timezone]">
        <option value=""><?php _l('select-timezone')?></option>
        <?php foreach(getTimezones() as $key => $name):?>
            <option value="<?php echo $key?>"><?php echo $name?></option>
        <?php endforeach?>
    </select>

    <?php if(config('enable-captcha', false)):?>
        <div class="captcha-container">
            <div class="g-recaptcha-pane" id="g-recaptcha-pane" data-sitekey="<?php echo config('captcha-site-key')?>"></div>
        </div>
    <?php endif?>

    <button class="btn btn-block btn-raised btn-primary mt-3 btn-lg"><?php _l('signup')?></button>

    <div class="clearfix mt-5">

        <a href="<?php echo url('login')?>" data-ajax="true" class="color-grey font-bg mt-5"><?php _l('login')?></a>
    </div>
</form>

