
<div class="welcome-title">
    <h5><?php _l('create-your-own-account')?></h5>
</div>

<form action="<?php echo getFullUrl(true)?>" method="post" class="general-form">
    <?php if(config('email-verification', false) or $C->request->input('message') == 'activate'):?>
        <div class="alert alert-warning " style="display: none;" id="activationEmailSuccess">
            <strong><?php _l('registeration-successful')?></strong><br/>
            <span><?php _l('activation-email-check')?></span>
        </div>
    <?php endif?>
    <div class="form-group">
        <label class="bmd-label-floating" for="fullName"><?php _l('full-name')?></label>
        <div class="input-group mb-2">

            <input type="text"  id="fullName" class="form-control" name="val[full_name]" >
            <div class="input-group-prepend">
                <div class="input-group-text"><i class="la la-user"></i></div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label  class="bmd-label-floating" for="emailAddress"><?php _l('email-address')?></label>
        <div class="input-group mb-2">

            <input id="emailAddress" type="text" placeholder="" class="form-control" name="val[email]" >
            <div class="input-group-prepend">
                <div class="input-group-text"><i class="la la-user"></i></div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label  class="bmd-label-floating" for="password"><?php _l('password')?></label>
                <div class="input-group mb-2">

                    <input type="password" id="password" placeholder="" class="form-control" name="val[password]" >
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="la la-lock"></i></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                <label  class="bmd-label-floating" for="confirm"><?php _l('confirm')?></label>
                <div class="input-group mb-2">

                    <input type="password" id="confirm" placeholder="" class="form-control" name="val[confirm]" >
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="la la-lock"></i></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php Hook::getInstance()->fire('signup.extend')?>

    <select class="form-control select-timezone" name="val[timezone]">
        <option value=""><?php _l('select-timezone')?></option>
        <?php foreach(getTimezones() as $key => $name):?>
            <option value="<?php echo $key?>"><?php echo $name?></option>
        <?php endforeach?>
    </select>

    <?php if(config('enable-captcha', false)):?>
        <div class="captcha-container">
            <div class="g-recaptcha-pane" id="g-recaptcha-pane" data-sitekey="<?php echo config('captcha-site-key')?>"></div>
        </div>
    <?php endif?>

    <button class="btn btn-block btn-raised btn-primary mt-3 btn-lg"><?php _l('signup')?></button>

    <div class="clearfix mt-5">

        <a href="<?php echo url('login')?>" data-ajax="true" class="color-grey font-bg mt-5"><?php _l('already-have-accoung')?></a>
    </div>
</form>

