<?php echo view('posts/header', array('active' => 'compose'))?>

<div class="content-body content-scroller modern-scroll ">

    <div class="container-1200">
        <form action="<?php echo getFullUrl()?>" method="post" class="general-form" id="postEditorForm">
            <div class="row ">

                <div class="col-md-3">
                    <div class="clearfix mt-4">
                        <div class="custom-control custom-checkbox ">
                            <input  type="checkbox" onchange="return PostEditor.toggleSelectAll(this)" class="custom-control-input" id="customCheckAccountAll">
                            <label class="custom-control-label" for="customCheckAccountAll"><?php _l('select-all-accounts')?></label>
                        </div>

                    </div>
                    <div class=" pt-3" style="background: #F5F5F5;">
                        <div class="account-selector-list clearfix ">

                            <?php foreach(model('social')->getAccounts() as $account):?>
                                <a href="" onclick="return PostEditor.addAccount('<?php echo $account['id']?>','<?php echo $account['username']?>', '<?php echo assetUrl($account['avatar'])?>')" class="each " data-id="<?php echo $account['id']?>" data-name="<?php echo $account['username']?>" data-avatar="<?php echo assetUrl($account['avatar'])?>">
                                    <div class="custom-control custom-checkbox mt-3">
                                        <input name="val[accounts][]" value="<?php echo $account['id']?>"  onchange="return PostEditor.selectAccount(this)"  type="checkbox" class="custom-control-input" id="customCheck<?php echo $account['id']?>">
                                        <label class="custom-control-label" for="customCheck<?php echo $account['id']?>"></label>
                                    </div>
                                    <div class="media">
                                        <img class="mr-3 mt-2" style="width: 30px;height:30px;border-radius:100px;" src="<?php echo assetUrl($account['avatar'])?>" alt="Generic placeholder image">
                                        <div class="media-body pt-1">
                                            <h6 class=" text--wrapping mt-2"><?php echo $account['username']?></h6>
                                        </div>
                                    </div>

                                </a>
                            <?php endforeach?>
                        </div>
                    </div>

                </div>
                <div class="col-md-9">
                    <div class="">
                        <div class="card shadow-1  pr-0">
                            <div class="card-header p-0">
                                <div class="nav-tabs-scrollable" style="height: 4rem;">
                                    <ul class="nav nav-justified nav-tabs post-editor-menu" id="composePostTypes" role="tablist">
                                        <li class="nav-item">
                                            <a aria-controls="home"  class="nav-link active" onclick="return PostEditor.switchType(this, 'media')"  href="#compose"  role="tab">
                                                <i class="icons icon-camera"></i>
                                                <span>
                                        <h6> <?php _l('post')?></h6>
                                        <?php _l('photo')?>
                                    </span>

                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a aria-controls="home"  class="nav-link" onclick="return PostEditor.switchType(this, 'album')"  href="#compose"  role="tab">
                                                <i class="icons icon-layers"></i>
                                                <span>
                                        <h6> <?php _l('album')?></h6>
                                                    <?php _l('photo')?>
                                    </span>

                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a aria-controls="home"  class="nav-link " onclick="return PostEditor.switchType(this, 'story')" href="#compose"  role="tab">
                                                <i class="icons icon-plus"></i>
                                                <span>
                                        <h6><?php _l('story')?></h6>
                                         <?php _l('photo')?>
                                    </span>

                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a aria-controls="home"  class="nav-link " onclick="return PostEditor.switchType(this, 'igtv')"  href="#compose"  role="tab">
                                                <i class="icons icon-screen-desktop"></i>
                                                <span>
                                        <h6> IGTV</h6>
                                                    <?php _l('video')?>
                                    </span>

                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a aria-controls="home"  class="nav-link " onclick="return PostEditor.switchType(this, 'live')" href="#compose"  role="tab">
                                                <i class="icons icon-camrecorder"></i>
                                                <span>
                                        <h6> <?php _l('live-video')?></h6>
                                                    <?php _l('video')?>
                                    </span>

                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                                <div class="media-select-container ">

                                <div class="card-header clearfix pt-2 pb-2" style="border-bottom: none;">
                                    <div class="float-left">
                                        <a href="" class="btn shadow-1" onclick="return PostEditor.clickUploadButton()"><?php _l('upload')?></a>
                                        <a href="" class="btn shadow-1" onclick="return Filemanager.open('PostEditor.chooseCallback')"><?php _l('choose-media')?> </a>

                                    </div>
                                    <div class="float-right">
                                        <a href="" onclick="return PostEditor.continueMediaSelect()" class="btn btn-secondary disabled" id="compose-media-continue"><?php _l('continue')?></a>
                                    </div>
                                </div>

                                <div class=" p-3" >
                                    <div class="file-drag-drop-container">
                                        <i class="las la-cloud-upload-alt"></i>
                                        <p><?php _l('drop-files-here')?></p>
                                        <div>
                                            <button type="button" class="btn btn-secondary" onclick="PostEditor.clickUploadButton()"><?php _l('browse-file')?></button>
                                        </div>

                                    </div>
                                    <div class="external-file-chooser clearfix">
                                        <div class="float-left">
                                            <?php _l('import-from')?>:
                                        </div>
                                        <div class="float-right">
                                            <a href="" class="btn shadow-none"><i class="lab la-google-drive"></i></a>
                                            <a href="" class="btn shadow-none"><i class="lab la-dropbox"></i></a>
                                            <a href="" class="btn shadow-none"><i class="las la-link"></i></a>
                                        </div>
                                    </div>
                                    <div class="selected-media-container clearfix">

                                    </div>
                                </div>
                            </div>

                            <div class="post-content-container hide">

                                <input type="hidden" name="val[post_type]" id="compose-type-input" value="media"/>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-8">
                                            <div class="clearfix">
                                                <div class="btn-group mt-4 shadow-none float-right" role="group">
                                                    <button type="button" onclick="return PostEditor.editMediaSelect()" class="btn btn-light  float-right"><?php _l('edit-media')?></button>
                                                    <button type="button" class="btn btn-outline-light  float-right " id="add-location-compose-btn" onclick="return PostEditor.openLocation()"><?php _l('add-location')?></button>
                                                </div>
                                            </div>
                                            <div class="modal  modal-right modal-right" tabindex="-1" id="addLocationModal" role="dialog">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content p-0">
                                                        <div class="modal-header">
                                                            <div class="form-group floating-label" style="width: 100%;">
                                                                <label class=""><?php _l('add-location')?></label>
                                                                <input  onkeyup="return PostEditor.fetchLocation(this)" type="text" class="form-control" />
                                                            </div>
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="content-scroller modern-scroll p-0 instagram-locations-container" >

                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" onclick="return PostEditor.closeLocation()" class="btn "><?php _l('continue')?></button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group mt-4">
                                                <h5><?php _l('caption')?></h5>
                                                <div class="post-editor-container">
                                                    <textarea class="form-control emoji-text" id="compose-editor" name="val[content]"></textarea>
                                                    <div class="editor-insert-btn-container">
                                                        <a href="" onclick="return loadTemplates(this)" data-type="captions" data-editor="#compose-editor"><i class="icons icon-layers"></i></a>
                                                        <a href="" onclick="return loadTemplates(this)" data-type="mention" data-editor="#compose-editor"><i class="las la-at"></i></a>
                                                        <a href="" onclick="return loadTemplates(this)" data-type="hashtag" data-editor="#compose-editor"><i class="las la-hashtag"></i></a>

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="first-comment-container hide">
                                                <h5><?php _l('first-comment')?></h5>
                                                <div class="post-editor-container">
                                                    <textarea class="form-control emoji-text" id="compose-first-comment-editor" name="val[first_comment]"></textarea>
                                                    <div class="editor-insert-btn-container">
                                                        <a href="" class="mtitle" title="<?php _l('insert-caption')?>" onclick="return loadTemplates(this)" data-type="captions" data-editor="#compose-first-comment-editor"><i class="icons icon-layers"></i></a>
                                                        <a href="" class="mtitle" title="<?php _l('insert-hashtag')?>" onclick="return loadTemplates(this)" data-type="mention" data-editor="#compose-first-comment-editor"><i class="las la-at"></i></a>
                                                        <a href="" class="mtitle" title="<?php _l('insert-mention')?>" onclick="return loadTemplates(this)" data-type="hashtag" data-editor="#compose-first-comment-editor"><i class="las la-hashtag"></i></a>

                                                    </div>
                                                </div>
                                            </div>

                                            <div class="story-link-container hide">
                                                <div class="form group floating-label">
                                                    <label><?php _l('story-link')?></label>
                                                    <input type="text" name="val[story_link]" class="form-control" />
                                                </div>
                                            </div>

                                            <div class="schedule-input-container mt-3 hide">
                                                <div class="input-group mb-2">
                                                    <div class="input-group-prepend">
                                                        <div class="input-group-text"><i class="icons icon-calendar"></i></div>
                                                    </div>
                                                    <?php
                                                    $date = null;
                                                    if ($C->request->input('date')) {
                                                        $dateObj = DateTime::createFromFormat('m/d/Y', $C->request->input('date'));
                                                        $date = $dateObj->format(getAdminDateFormat().' h:i A');

                                                    }

                                                    ?>
                                                    <input type="text"  autocomplete="off" name="val[post_time]" class="form-control datepicker-input-time form-control-sm" style="height: 35px;"  value="<?php echo $date ? $date : date(getAdminDateFormat().' h:i a')?>">
                                                </div>
                                            </div>

                                            <div class="mt-3 row posts-action-toggle">
                                                <div class="col-4">
                                                    <input type="hidden" name="val[schedule]" value="0"/>
                                                    <div class="custom-control custom-checkbox">

                                                        <input value="1" name="val[schedule]" onchange="return PostEditor.toggleSchedule(this, '.schedule-input-container')" type="checkbox" class="custom-control-input" id="enableSchedule">
                                                        <label class="custom-control-label" for="enableSchedule"><?php _l('schedule')?></label>
                                                    </div>
                                                </div>
                                                <div class="col-4 first-comment-switch-container">
                                                    <input type="hidden" name="val[enable_first_comment]" value="0"/>
                                                    <div class="custom-control custom-checkbox">
                                                        <input name="val[enable_first_comment]" value="1" onchange="return PostEditor.toggleFirstComment(this)"  type="checkbox" class="custom-control-input" id="enableFirstComment">
                                                        <label class="custom-control-label" for="enableFirstComment"><?php _l('add-first-comment')?></label>
                                                    </div>
                                                </div>
                                                <div class="col-4 friend-story-container hide">
                                                    <input   type="hidden" value="0"  name="val[friend_story]">
                                                    <div class="custom-control custom-checkbox">
                                                        <input value="1"  type="checkbox" class="custom-control-input" name="val[friend_store]" id="enableFriendStory">
                                                        <label class="custom-control-label" for="enableFriendStory"><?php _l('friends-story')?></label>
                                                    </div>
                                                </div>
                                            </div>



                                            <div class="post-buttons">
                                                <div class="btn-group mt-4 shadow-none float-right" role="group" >
                                                    <button type="button" onclick="PostEditor.submitPost(true)" class="btn  btn-light btn-block  btn-lg"><?php _l('send-to-draft')?></button>
                                                    <button type="button" onclick="PostEditor.submitPost()" class="btn  btn-block btn-primary  btn-lg" id="publish-btn"><?php _l('publish-now')?></button>
                                                    <button type="button" onclick="PostEditor.submitPost()" class="btn  btn-block btn-primary  btn-lg hide" id="schedule-now-btn"><?php _l('schedule-now')?></button>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="card shadow-1 post-preview" >
                                                <div class="regular-instagram-post ">
                                                    <div class="card-header" style="text-align:center;border-bottom: solid 1px #F5F5F5;">
                                                        <img src="<?php echo assetUrl('assets/images/instagram-logo.png')?>"/>
                                                    </div>
                                                    <div class="instagram-post-header">
                                                        <div class="avatar"></div>
                                                        <div class="header-info">
                                                            <div></div>
                                                            <div></div>
                                                        </div>
                                                    </div>
                                                    <div class="instagram-post-content">

                                                    </div>
                                                    <div class="instagram-post-caption">
                                                        <div></div>
                                                        <div></div>
                                                    </div>
                                                </div>
                                                <div class="video-instagram-post hide">

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>

            </div>
        </form>
    </div>
</div>

<form method="post" style="position:relative;display: none;"  data-upload="#upload-progress" action="<?php echo url('files')?>" enctype="multipart/form-data" class="general-form filemanager-uploader">
    <input type="hidden" name="val[upload]" value="1"/>
    <input type="hidden" name="val[upload_result]" value="PostEditor.uploadResult"/>
    <input type="hidden" name="val[folder_id]" value="0"/>
    <input id="compose-file-input" multiple onchange="validate_file_size(this, 'image-video','submit_file_upload')" type="file" name="file[]" style="position:absolute;top: 0;width: 100%;height: 100%;opacity: 0;z-index: 99;cursor: pointer">
    <button class="btn btn-secondary"></button>
</form>

