<?php echo view('posts/header', array('active' => 'drafts'))?>

<div class="content-body content-scroller modern-scroll ">
    <div class="container-1200">
        <div class="row">
            <div class="col-md-3 side-content">
                <h4><i class="icons icon-menu"></i> Post Filter</h4>
                <div class="clearfix mt-4">
                    <div class="custom-control custom-checkbox ">
                        <input data-url="<?php echo url('posts/drafts')?>"  type="checkbox" <?php echo ($selectedAccounts[0] == 'all')? 'checked':null?> onchange="return PostEditor.togglePageSelectAll(this)" class="custom-control-input account-select-all-input" id="customCheckAccountAll">
                        <label class="custom-control-label" for="customCheckAccountAll"><?php _l('select-all-accounts')?></label>
                    </div>

                </div>
                <div class="account-selector-list clearfix ">

                    <?php foreach(model('social')->getAccounts() as $account):?>
                        <a href="" onclick="return PostEditor.addSelectAccount(this)" data-id="<?php echo $account['id']?>" class="each "  data-name="<?php echo $account['username']?>" data-avatar="<?php echo assetUrl($account['avatar'])?>">
                            <div class="custom-control custom-checkbox mt-3">
                                <input <?php echo ($selectedAccounts[0] == 'all' or in_array($account['id'], $selectedAccounts)) ? 'checked':null?> data-id="<?php echo $account['id']?>" name="val[accounts][]" value="<?php echo $account['id']?>"  onchange="return PostEditor.addSelectAccount(this)"  type="checkbox" class="custom-control-input each-account-input" id="customCheck<?php echo $account['id']?>">
                                <label class="custom-control-label" for="customCheck<?php echo $account['id']?>"></label>
                            </div>
                            <div class="media">
                                <img class="mr-3 mt-2" style="width: 30px;height:30px;border-radius:100px;" src="<?php echo assetUrl($account['avatar'])?>" alt="Generic placeholder image">
                                <div class="media-body pt-1">
                                    <h6 class=" text--wrapping mt-2"><?php echo $account['username']?></h6>
                                </div>
                            </div>

                        </a>
                    <?php endforeach?>
                </div>
            </div>
            <div class="col-md-9 main-content">
                <div class="card shadow-1  pr-0">
                    <div class="card-header clearfix border-none">
                        <div class="float-left">
                            <div class="custom-control custom-checkbox mt-1">
                                <input  type="checkbox" onchange="toggleSelectItemsAll(this)" class="custom-control-input select-item-all" id="customCheckDraftAll">
                                <label class="custom-control-label" for="customCheckDraftAll"><?php _l('select-all')?></label>
                            </div>
                        </div>
                        <div class="float-right">
                            <div class="dropdown">
                                <button class="btn btn-light dropdown-toggle disabled  shadow-1" type="button" id="selectActionBtn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Bulk action
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" onclick="return doSelectForm('delete')" href="#">Delete</a>
                                    <a class="dropdown-item" onclick="return doSelectForm('schedule')" href="#">Schedule now</a>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form  action="<?php echo getFullUrl()?>" class="general-form select-form" method="post">
                            <input type="hidden" name="val[action]" value="" id="select-action-input"/>
                            <?php foreach($posts->results() as $post): $account = model('social')->findAccount($post['account']);$postData = perfectUnserialize($post['type_data'])?>
                                <div class="card mb-4 shadow-none" style="border-top: solid 1px #F5F5F5;">
                                    <div class=" row">
                                        <div class="col-md-6">
                                            <div class="row">
                                                <div class="col-2">
                                                    <div class="custom-control custom-checkbox mt-3">
                                                        <input onchange="processSelectItems(this)" data-id="<?php echo $post['id']?>" name="val[posts][]" value="<?php echo $post['id']?>"    type="checkbox" class="custom-control-input select-item-input" id="customCheckList<?php echo $post['id']?>">
                                                        <label class="custom-control-label" for="customCheckList<?php echo $post['id']?>"></label>
                                                    </div>
                                                </div>
                                                <div class="col-10">
                                                    <div class="media">
                                                        <img class="mr-3 mt-2" style="width: 30px;height:30px;border-radius:100px;" src="<?php echo assetUrl($account['avatar'])?>" alt="Generic placeholder image">
                                                        <div class="media-body pt-1">
                                                            <h6 class=" text--wrapping mt-2"><?php echo $account['username']?></h6>
                                                        </div>
                                                    </div>

                                                    <h6 class="bold mt-3"><?php _l('caption')?>:</h6>
                                                    <p><?php echo $postData['content']?></p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="row">
                                                <div class="col-md-8">
                                                    <div class="list-post-preview">
                                                        <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
                                                            <ol class="carousel-indicators">
                                                                <?php $i = 0; foreach($postData['media'] as $media):?>
                                                                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="<?php echo ($i == 0) ? 'active':null?>"></li>
                                                                    <?php $i++; endforeach?>
                                                            </ol>
                                                            <div class="carousel-inner">
                                                                <?php $i = 0; foreach($postData['media'] as $media):?>
                                                                    <?php if(isImage($media)):?>
                                                                        <div style="background-image: url(<?php echo assetUrl($media)?>);" class="carousel-item <?php echo ($i == 0) ? 'active':null?>"></div>
                                                                    <?php else:?>
                                                                        <div class="carousel-item <?php echo ($i == 0) ? 'active':null?>">
                                                                            <div class="video-content"><video src="<?php echo assetUrl($media)?>"></video></div>
                                                                        </div>
                                                                    <?php endif?>
                                                                    <?php $i++; endforeach?>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="post-list-links mt-3">
                                                        <?php
                                                            $medias = array();
                                                            foreach($postData['media'] as $media) {
                                                                $medias[]  = array(
                                                                        'file' => assetUrl($media),
                                                                    'type' => isImage($media) ? 'image': 'video'
                                                                );
                                                            }
                                                        ?>
                                                        <a href="" class="" data-media='<?php echo json_encode($medias)?>' data-type="<?php echo $post['type']?>" onclick="return PostEditor.preview(this)"><i class="las la-eye"></i>  Preview</a>
                                                        <a href="<?php echo url('posts')?>?id=<?php echo $post['id']?>" data-ajax="true" class=""><i class="las la-pen"></i>  Edit Draft</a>
                                                        <a href="" class=""><i class="las la-check"></i>  Publish Now</a>
                                                    </div>


                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach;?>
                        </form>

                        <?php echo $posts->links(array('accounts' => implode(',', $selectedAccounts)));?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

