<?php if($results):?>
<div class="list-group list-group-flush">
    <?php foreach($results as $result):?>
        <div  class="list-group-item list-group-item-action" onclick="return PostEditor.selectLocation(this)">
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio"  id="customRadioInline<?php echo md5($result->location->name)?>" value='<?php echo serialize($result)?>' name="val[selected_location]" class="custom-control-input">
                <label class="custom-control-label" for="customRadioInline<?php echo md5($result->location->name)?>">
                    <?php echo str_limit($result->location->name, 40)?><br/>
                    <span class="text-muted"><?php echo str_limit($result->location->address, 40)?></span>
                </label>
            </div>
        </div>
    <?php endforeach?>
</div>
<?php endif?>
