<div class="cover-pane-container" id="new-compose-modal">
    <div class="cover-pane">
        <div class="content-top" style="background: none;border-bottom:none">
            <div class="right-actions pt-2">
                <a href="" onclick="return PostEditor.preview()" class="btn btn-light shadow-none"><i class="las la-eye"></i> <?php _l('preview')?></a>

                <a href="" onclick="return PostEditor.close(this)" class="btn btn-light post-editor-close-btn shadow-none" style="min-width: auto"><i class="las la-times"></i></a>
            </div>
        </div>
        <form action="<?php echo url('publishing')?>" method="post" class="general-form" id="postEditorForm">
            <input type="hidden" name="val[edit_post]" class="edit-post-input"/>
        <div class="content-body  content-body-with-tabs pt-0 content-scroller" data-height="0" style="overflow: auto">
            <div class="post-editor-container">
                <div class="media-select-container">
                    <input type="hidden" name="val[media]" class="selected-media-input"/>
                    <div class="first">
                        <i class="las la-cloud-upload-alt"></i>
                    </div>
                    <div class="clearfix more-media">
                        <div class="each"></div>
                        <div class="each"></div>
                        <div class="each"></div>
                        <div class="each "></div>
                    </div>
                    <a href="" onclick="return Filemanager.open('PostEditor.chooseCallback')" class="btn btn-light btn-block shadow-none mt-2"><?php _l('add-media')?></a>
                </div>

                <div class="main">
                    <div class="labels dropdown">
                        <a href="" data-toggle="dropdown" class="btn btn-light"><?php _l('add-label')?></a>
                        <div class="dropdown-menu" style="width: 250px">
                            <?php
                            $labels = perfectUnserialize($C->workspace['labels']);
                            if (!$labels) $labels = array();
                            ?>
                            <?php foreach($labels as $label):list($r, $g, $b) = sscanf($label['color'], "#%02x%02x%02x");?>
                                <a onclick="return PostEditor.addLabel('rgba(<?php echo $r?>,<?php echo $g?>,<?php echo $b?>,0.1)','<?php echo $label['color']?>','<?php echo $label['title']?>')" class="dropdown-label" href="" style="background-color:rgba(<?php echo $r?>,<?php echo $g?>,<?php echo $b?>,0.1);color:<?php echo $label['color']?>;border-color:<?php echo $label['color']?>"><?php echo $label['title']?></a>
                            <?php endforeach;?>
                        </div>
                        <span class="label-inputs">

                        </span>
                    </div>
                    <textarea data-counter=".post-editor-character-count" class="form-control emoji-text" placeholder="<?php _l('editor-placeholder')?>" id="compose-editor" name="val[content]"></textarea>
                    <div class="editor-insert-btn-container clearfix">
                        <div class="float-left">
                            <a href="" class="mtitle" title="<?php _l('choose-saved-captions')?>" onclick="return loadTemplates(this)" data-type="captions" data-editor="#compose-editor"><i class="icons icon-layers"></i></a>
                            <a href="" class="mtitle" title="<?php _l('choose-saved-hashtags')?>" onclick="return loadTemplates(this)" data-type="hashtag" data-editor="#compose-editor"><i class="las la-hashtag"></i></a>
                        </div>
                        <div class="float-right">
                            <a href="" class="btn shadow-none" style="position:relative;display:none"><span style="position:absolute;right: 3px;top: -5px;font-size:9px;text-transform: capitalize" class="badge badge-success"><?php _l('new')?></span><?php _l('add-follow-up-comments')?></a>
                            <span class="" style="display: inline-block"><span class="post-editor-character-count">200</span> / ♾️</span>
                        </div>
                    </div>

                    <hr/>
                    <div class="row mb-3">
                        <div class="col-4">
                            <h5 class="bold mb-3 mt-3"><?php _l('schedule-your-post')?></h5>
                            <div class="custom-control custom-radio">
                                <input onchange="PostEditor.switchScheduleType(this)" type="radio" value="0" checked id="customRadio1" name="val[type]" class="custom-control-input draft-check-input">
                                <label class="custom-control-label" for="customRadio1"><?php _l('save-as-draft')?></label>
                            </div>
                           <?php if(!$C->workspace['approval']):?>
                               <div class="custom-control custom-radio">
                                   <input  onchange="PostEditor.switchScheduleType(this)" type="radio" value="1" id="customRadio2" name="val[type]" class="custom-control-input">
                                   <label class="custom-control-label" for="customRadio2"><?php _l('post-now')?></label>
                               </div>
                            <?php endif?>

                            <div class="custom-control custom-radio">
                                <input  onchange="PostEditor.switchScheduleType(this)" type="radio" value="2" id="customRadio4" name="val[type]" class="custom-control-input scheduled-check-input">
                                <label class="custom-control-label" for="customRadio4"><?php _l('choose-date-time')?></label>
                            </div>
                            <div class="custom-control custom-radio">
                                <input  onchange="PostEditor.switchScheduleType(this)" type="radio" value="3" id="customRadio3" name="val[type]" class="custom-control-input">
                                <label class="custom-control-label" for="customRadio3"><?php _l('auto-schedule')?></label>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="clearfix">
                                <div class="float-left" style="width:35% ">
                                    <h5 class="mt-3" style="font-size: 13px"><?php _l('social-accounts')?>:</h5>
                                </div>
                                <div class="float-right post-editor-accounts" style="width: 65%">
                                    <?php echo view('posts/account-picker', array('reload' => 0, 'container' => 'post-editor-accounts', 'postEditor' => true))?>
                                </div>
                            </div>

                            <div class="schedule-input-container disabled mt-3 ">
                                <div class="cover"></div>
                                <h6><?php _l('choose-date-time')?></h6>
                                <input type="hidden" value="0" name="val[schedule]"/>
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text"><i class="icons icon-calendar"></i></div>
                                    </div>
                                    <?php
                                    $date = null;
                                    if ($C->request->input('date')) {
                                        $dateObj = DateTime::createFromFormat('m/d/Y', $C->request->input('date'));
                                        $date = $dateObj->format(getAdminDateFormat().' h:i ');

                                    }

                                    ?>
                                    <input type="text"  autocomplete="off" name="val[post_time]" id="post-editor-schedule-time-input" class="form-control datepicker-input-time form-control-sm" style="height: 35px;"  value="<?php echo $date ? $date : date(getAdminDateFormat().' h:i')?>">
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr/>
                    <div class="modal-footer m-0  p-0">
                        <div class="post-buttons m-0">
                            <button type="button" onclick="PostEditor.submitPost()" class="btn  btn-block btn-primary  btn-lg " id="schedule-now-btn"><?php _l('continue')?></button>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        </form>


    </div>
</div>

<div class="modal  modal-right"  tabindex="-1" id="postPreviewModal" role="dialog">
    <div class="modal-dialog" role="document">
        <form action="<?php echo url('files')?>" method="post" class="general-form short-form">
            <div class="modal-content p-0">
                <div class="modal-header">
                    <h5 class="modal-title"><?php _l('post-preview')?></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <ul class="nav nav-tabs justify-content-center" style="border-top: solid 1px #F1F3F4">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#facebook-preview" role="tab"><i style="font-size: 25px" class="lab la-facebook-f"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#instagram-preview" role="tab"><i style="font-size: 25px" class="lab la-instagram"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#twitter-preview" role="tab"><i style="font-size: 25px" class="lab la-twitter"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " data-toggle="tab" href="#linkedin-preview" role="tab"><i style="font-size: 25px" class="lab la-linkedin"></i></a>
                    </li>
                </ul>
                <div class="modal-body content-scroller">
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="facebook-preview" role="tabpanel" aria-labelledby="home-tab">
                            <div class="preview shadow-1">
                                <div class="head">
                                    <div class="avatar"></div>
                                    <div class="info clearfix">
                                        <div class="float-left">
                                            <div class="title"></div>
                                            <div class="time"><?php _l('just-now')?></div>
                                        </div>
                                        <div class="float-right">
                                            <i class="las la-ellipsis-h"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="caption">
                                    <div class="placeholder"><div></div><div></div></div>
                                    <div class="text"></div>
                                </div>
                                <div class="medias-container">

                                </div>
                                <div class="foot">
                                    <ul class="clearfix">
                                        <li><i class="las la-thumbs-up"></i> <?php _l('like')?></li>
                                        <li><i class="las la-comment-alt"></i> <?php _l('comment')?></li>
                                        <li><i class="icons icon-action-redo"></i> <?php _l('share')?></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="instagram-preview" role="tabpanel" aria-labelledby="profile-tab">
                            <div class="preview shadow-1">
                                <div class="head">
                                    <div class="avatar"></div>
                                    <div class="info clearfix">
                                        <div class="title float-left"></div>
                                        <span class="float-right"><i class="las la-ellipsis-v"></i></span>
                                    </div>
                                </div>
                                <div class="medias-container"></div>
                                <div class="foot clearfix">
                                    <div class="float-left">
                                        <ul>
                                            <li><i class="icons icon-heart"></i></li>
                                            <li><i class="icons icon-bubble"></i></li>
                                            <li><i class="icons icon-paper-plane"></i></li>
                                        </ul>
                                    </div>
                                    <div class="float-right">
                                        <i class="las la-bookmark"></i>
                                    </div>
                                </div>
                                <div class="caption">
                                    <div class="text"></div>
                                </div>
                                <div class="time"><?php echo strtoupper(l('just-now'))?></div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="twitter-preview" role="tabpanel" aria-labelledby="contact-tab">
                            <div class="preview shadow-1">
                                <div class="head">
                                    <div class="avatar"></div>
                                    <div class="info clearfix">
                                        <div class="float-left">
                                            <div class="title"></div>
                                            <div class="caption">
                                                <div class="placeholder"><div></div><div></div></div>
                                                <div class="text"></div>
                                            </div>
                                        </div>
                                        <div class="float-right">
                                            <i class="las la-angle-down"></i>
                                        </div>
                                    </div>
                                    <div class="twitter-body">
                                        <div class="medias-container"></div>
                                        <div class="foot">
                                            <ul class="clearfix">
                                                <li><i class="icons icon-bubble"></i></li>
                                                <li><i class="icons icon-heart"></i></li>
                                                <li><i class="las la-retweet"></i></li>
                                                <li><i class="icons icon-share-alt"></i></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="linkedin-preview" role="tabpanel" aria-labelledby="contact-tab">
                            <div class="preview shadow-1">
                                <div class="head">
                                    <div class="avatar"></div>
                                    <div class="info">
                                        <div class="title"></div>
                                        <div class="time"><?php _l('just-now')?></div>
                                    </div>
                                </div>
                                <div class="caption">
                                    <div class="placeholder"><div></div><div></div></div>
                                    <div class="text"></div>
                                </div>
                                <div class="medias-container">

                                </div>
                                <div class="foot">
                                    <ul>
                                        <li><i class="las la-thumbs-up"></i> <?php _l('like')?></li>
                                        <li><i class="las la-comment-alt"></i> <?php _l('comment')?></li>
                                        <li><i class="icons icon-action-redo"></i> <?php _l('share')?></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>
<form method="post" style="position:relative;display: none;"  data-upload="#upload-progress" action="<?php echo url('files')?>" enctype="multipart/form-data" class="general-form filemanager-uploader">
    <input type="hidden" name="val[upload]" value="1"/>
    <input type="hidden" name="val[upload_result]" value="PostEditor.uploadResult"/>
    <input type="hidden" name="val[folder_id]" value="0"/>
    <input id="compose-file-input" multiple onchange="validate_file_size(this, 'image-video','submit_file_upload')" type="file" name="file[]" style="position:absolute;top: 0;width: 100%;height: 100%;opacity: 0;z-index: 99;cursor: pointer">
    <button class="btn btn-secondary"></button>
</form>

