<div class="each-container">
    <div class="each each-account ">
        <?php if($account['status']):?>
            <div class="mb-3"><span class="badge badge-pill badge-warning"><?php _l('active')?></span></div>
        <?php else:?>
            <div class="mb-3"><span class="badge badge-pill badge-danger"><?php _l('disabled')?></span></div>
        <?php endif?>


        <div class="media">
            <img class="mr-3" style="width: 30px;height:30px;border-radius:100px;" src="<?php echo assetUrl($account['avatar'])?>" alt="Generic placeholder image">
            <div class="media-body">
                <h6 class="bold text--wrapping"><?php echo $account['username']?></h6>
                <p class="text-muted m-0 p-0 text--wrapping"><?php echo $account['full_name']?></p>
            </div>
        </div>

        <div class="each-footer clearfix">
            <div class="float-left" style="width:60%">

                <a data-ajax="true" href="<?Php echo url('dashboard', array('switch' => $account['username']))?>" title="<?php _l('set-active-account')?>" class="btn-float btn btn-sm shadow-none mtitle <?php echo ($C->selectedAccount['id'] == $account['id']) ? 'btn-primary' : null?> "><i class="las la-check"></i></a>
            </div>
            <div class="float-right " style="width:40%">
                <a href="<?php echo url('accounts', array('action' => 'delete', 'id' => $account['id']))?>" data-ajax-action="true" class=" btn btn-float btn-sm  float-right shadow-none confirm mtitle" title="<?php _l('delete-account')?>" data-message="<?php _l('confirm-delete-account')?>"><i class="las la-trash-alt"></i></a>

            </div>

        </div>
    </div>
</div>