<div class="table-row clearfix each-account-<?php echo $account['id']?>">
    <div class="each clearfix" style="width: 10%">
        <div class="left"></div>
        <div class="right">
            <div class="custom-control custom-checkbox">
                <input type="checkbox" onclick="return Account.selectAccount(this, '<?php echo $account['id']?>')" data-id="<?php echo $account['id']?>" class="custom-control-input account-checkbox" id="customCheckInline<?php echo $account['id']?>">
                <label class="custom-control-label" for="customCheckInline<?php echo $account['id']?>"></label>
            </div>
        </div>
    </div>
    <div class="each clearfix" style="width: 10%">
        <div class="left"><?php _l('picture')?></div>
        <div class="right">
            <div class="avatar-sm-round" style="background-image: url(<?php echo assetUrl($account['avatar'])?>)"></div>
        </div>
    </div>
    <div class="each clearfix" style="width:35%">
        <div class="left"><?php _l('profile-pro')?></div>
        <div class="right">
            <h6 class="bold text--wrapping"><?php echo $account['username']?></h6>
        </div>
    </div>

    <div class="each clearfix" style="width:30%">
        <div class="left"><?php _l('social-type')?></div>
        <div class="right">
            <h6 class=" text--wrapping"><?php echo ucwords($account['social_type'])?></h6>
        </div>
    </div>


    <div class="each clearfix" style="width:15%">
        <div class="left"><?php _l('actions')?></div>
        <div class="right">
            <div class="btn-group shadow-none">
                <a href=""  class="btn btn-light  shadow-none btn-sm mtitle" title="<?php _l('edit-account')?>"><i class="las la-pencil"></i></a>
                <a href="" onclick="return Account.multiAction('delete-action', '<?php echo $account['id']?>')"  class="btn btn-light  shadow-none btn-sm mtitle" title="<?php _l('delete')?>"><i class="las la-trash-alt"></i></a>
            </div>
        </div>
    </div>
</div>