<div class="each-container each-account-<?php echo $account['id']?>">
    <div class="each each-account ">
        <div class="custom-control custom-checkbox show-hover">
            <input type="checkbox" onclick="return Account.selectAccount(this, '<?php echo $account['id']?>')" data-id="<?php echo $account['id']?>" class="custom-control-input account-checkbox" id="customCheck<?php echo $account['id']?>">
            <label class="custom-control-label" for="customCheck<?php echo $account['id']?>"></label>
        </div>
        <i class="social-icon show-hover <?php echo $account['social_type']?>-color  lab la-<?php echo ($account['social_type'] == 'facebook') ? 'facebook-f': $account['social_type']?>"></i>
        <div class="dropleft show-hover">
            <a class="confirm" data-ajax-action="true" href="<?php echo url('accounts', array('action' => 'delete', 'id' => $account['id']))?>" data-message="<?php _l('confirm-delete-account')?>"><i class="las la-trash-alt"></i></a>

        </div>
        <div class="media-container">
            <div class="account-media" style="background-image: url(<?php echo assetUrl($account['avatar'])?>)">
                <?php if($account['status']):?>
                    <div class="mb-3"><span class="badge badge-pill badge-light "><?php _l('active')?></span></div>
                <?php else:?>
                    <div class="mb-3"><span class="badge badge-pill badge-danger"><?php _l('disabled')?></span></div>
                <?php endif?>
            </div>
        </div>
        <div class="info">
            <h6 class="bold truncate"><?php echo $account['username']?></h6>
            <?php echo ucwords($account['social_account_type'])?>
        </div>
    </div>
</div>