<div class="pane-container pane-container-sm" style="height: calc(100vh - 63px)">
    <?php echo view('profile/menu')?>
    <div class="pane-right">
        <div class="content-top">

            <div class="nav-tabs-scrollable">
                <ul class="nav  nav-tabs icon-navs" id="justifiedTab" role="tablist">
                    <li class="nav-item">
                        <a aria-controls="home" aria-selected="true" class="nav-link <?php echo ($page == 'all')? 'active': null?>" data-ajax="true" href="<?php echo url('accounts')?>"  role="tab">All</a>
                    </li>
                    <li class="nav-item">
                        <a aria-controls="home" aria-selected="true" class="nav-link <?php echo ($page == 'facebook')? 'active': null?>" data-ajax="true" href="<?php echo url('accounts/facebook')?>"  role="tab"><i style="" class="lab la-facebook-f"></i></a>
                    </li>
                    <li class="nav-item">
                        <a aria-controls="home" aria-selected="true" class="nav-link <?php echo ($page == 'instagram')? 'active': null?>" data-ajax="true" href="<?php echo url('accounts/instagram')?>" role="tab"><i style=""  class="lab la-instagram"></i></a>
                    </li>
                    <li class="nav-item">
                        <a aria-controls="home" aria-selected="true" class="nav-link <?php echo ($page == 'twitter')? 'active': null?>" data-ajax="true" href="<?php echo url('accounts/twitter')?>"  role="tab"><i style=""  class="lab la-twitter"></i></a>
                    </li>
                    <li class="nav-item">
                        <a aria-controls="home" aria-selected="true" class="nav-link <?php echo ($page == 'linkedin')? 'active': null?>" data-ajax="true" href="<?php echo url('accounts/linkedin')?>"  role="tab"><i style=""  class="lab la-linkedin"></i></a>
                    </li>
                </ul>
            </div>
            <div class="right-actions">
                <form class="form-inline" style="display: inline-block">
                    <div class="form-group floating-label">
                        <label ><?php _l('search-accounts')?></label>
                        <input onkeyup="return Account.search(this)" type="text" class="form-control mb-2 mr-sm-2" >
                    </div>
                </form>
                <div class="btn-group shadow-none">
                    <a href="" onclick="return Account.changeView(this, 'grid')" class="btn btn-light change-view-btn active shadow-none btn-sm"><i class="icons icon-grid"></i></a>
                    <a href="" onclick="return Account.changeView(this, 'list')"  class="btn btn-light change-view-btn shadow-none btn-sm"><i class="las la-list"></i></a>
                </div>
                <a href="" onclick="return Socialpost.openPane('#new-account-modal')" class="btn btn-primary shadow-none"  style="min-width: auto"><i class="las la-plus"></i> Connect account</a>

                <div class="dropleft" style="display: inline-block">
                    <a href="" data-toggle="dropdown" class="btn btn-light shadow-none" style="min-width: auto"><i class="las la-bars"></i></a>
                    <div class="dropdown-menu-lg dropdown-menu">
                        <a href="" class="dropdown-item" onclick="return Account.multiAction('delete-action')"><i class="las la-trash-alt"></i> Delete accounts</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body content-scroller " style="overflow: auto">
            <div  id="accounts-container">
                <?php if($page != 'all'):?>
                    <div class="clearfix">
                        <h4 class="float-left"><?php echo ucwords($page)?> <?php echo ($page == 'facebook') ? 'Pages & Groups' : 'accounts'?> </h4>
                        <div class="float-right">
                            <?php if($page == 'facebook'):?>
                                <a href="" data-target="#newFacebookAccountModal" data-toggle="modal"  class="btn btn-light shadow-none mtitle" title="Refresh accounts"  style="min-width: auto"><i class="las la-redo-alt"></i></a>
                            <?php elseif($page == 'twitter'):?>

                            <?php elseif($page == 'linkedin'):?>

                            <?php else:?>

                            <?php endif?>
                        </div>
                    </div>
                    <hr/>
                <?php endif?>
                <?php $accounts = model('social')->getAccounts(null, null, $page)?>
                <?php echo view('account/list', array('accounts' => $accounts))?>
            </div>
        </div>
    </div>
</div>


<div class="modal fade bd-example-modal-sm" id="accountOptionModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered ">
        <div class="modal-content shadow-10">

        </div>
    </div>
</div>