<div class="content-top">
    <h3><?php _l('accounts')?></h3>
</div>

<div class="content-body">
    <div class="row">
        <div class="col-md-10">
            <div class="accounts-add-progress clearfix">
                <div class="progress-container">
                    <div class="progress" style="height: 20px;">
                        <div class="progress-bar progress-purple"  role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </div>
                <div class="text-container">
                    1 / & added
                </div>
            </div>
            <div class="grid-container clearfix">
                <div class="each-container">
                    <a href="" class="each each-add shadow-1" data-toggle="modal" data-target="#addAccountModal"><i class="las la-plus-circle"></i></a>
                </div>

                <?php foreach(model('social')->getAccounts() as $account):?>
                    <div class="each-container">
                        <div class="each each-account shadow-1">
                            <?php if($account['status']):?>
                                <div class="mb-3"><span class="badge badge-pill badge-success"><?php _l('active')?></span></div>
                            <?php else:?>
                                <div class="mb-3"><span class="badge badge-pill badge-danger"><?php _l('disabled')?></span></div>
                            <?php endif?>


                            <div class="media">
                                <img class="mr-3" style="width: 30px;height:30px;border-radius:100px;" src="<?php echo assetUrl($account['avatar'])?>" alt="Generic placeholder image">
                                <div class="media-body">
                                    <h6 class="bold text--wrapping"><?php echo $account['username']?></h6>
                                    <p class="text-muted m-0 p-0 text--wrapping"><?php echo $account['full_name']?></p>
                                </div>
                            </div>

                            <div class="each-footer clearfix">
                                <div class="float-left" style="width:60%">
                                    <a data-ajax="true" href="<?Php echo url('dashboard', array('switch' => $account['username']))?>" class=" btn-block btn btn-primary "><?php _l('enter')?></a>
                                </div>
                                <div class="float-right " style="width:40%">
                                    <a href="<?php echo url('accounts', array('action' => 'delete', 'id' => $account['id']))?>" data-ajax-action="true" class=" btn btn-float btn-sm  float-right shadow-none confirm mtitle" title="<?php _l('delete-account')?>" data-message="<?php _l('confirm-delete-account')?>"><i class="las la-trash-alt"></i></a>

                                </div>

                            </div>
                        </div>
                    </div>

                <?php endforeach?>
            </div>
        </div>
        <div class="col-md-2">
            <div class="side-help">
                <h3><?php _l('add-account')?></h3>
                <p>
                    <?php _l('add-account-help-note')?>
                </p>
            </div>
        </div>
    </div>
</div>

