<?php if(empty($accounts)):?>
    <div class="empty-result">
        <img src="<?php echo assetUrl('styles/main/images/empty.png')?>"/>

        <h5><?php _l('no-accounts-added-yet')?> </h5>

        <a href="" class="btn btn-primary" onclick="return Timably.openPane('#new-account-modal')"><?php _l('connect-account')?></a>
    </div>
<?php else:?>
    <div class="grid-container clearfix">
        <?php foreach($accounts as $account):?>
            <?php echo view('account/display', array('account' => $account));?>
        <?php endforeach?>
    </div>
    <div class="list-container">
        <div class="modern-table">
            <div class="table-body">
                <?php foreach($accounts as $account):?>
                    <?php echo view('account/display-list', array('account' => $account));?>
                <?php endforeach?>
            </div>
        </div>
    </div>
<?php endif?>