<div class="cover-pane-container" id="new-account-modal">
    <div class="cover-pane">
        <div class="content-top">
            <h5 class="pt-2"><?php _l('connect-your-account')?></h5>
            <div class="right-actions pt-2">
                <a href="" onclick="return Socialpost.closePane(this)" class="btn shadow-none"><?php _l('go-back')?></a>
            </div>
        </div>

        <div class="content-body content-scroller content-body-with-tabs">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-6">
                    <ul class="connect-account-btn">
                        <li><a href="" class="facebook-bg " data-toggle="modal" data-target="#newFacebookAccountModal "><i class="lab la-facebook-f"></i> <?php _l('add-facebook')?></a> </li>
                        <li><a href="" class="instagram-bg" data-toggle="modal" data-target="#newInstagramAccountModal"><i class="lab la-instagram"></i> <?php _l('add-instagram')?></a> </li>
                        <li><a href="<?php echo url('accounts/twitter?auth=true')?>" class="twitter-bg ajax-action" ><i class="lab la-twitter"></i> <?php _l('add-twitter')?></a> </li>
                        <li><a href="<?php echo url('accounts/linkedin?auth=true')?>" class="linkedin-bg ajax-action"><i class="lab la-linkedin-in"></i> <?php _l('add-linkedin')?></a> </li>
                        <li><a href="" class="google-bg"><i class="lab la-google"></i> <?php _l('add-google-bussiness')?></a> </li>
                                <li><a href="" class="telegram-bg"><i class="lab la-telegram"></i> <?php _l('add-telegram')?></a> </li>
                    </ul>
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
    </div>
</div>