<div class="content-top">
    <div class="clearfix">
        <div class="float-left">
            <h3><?php _l('email-templates')?> </h3>
            <p class="text-muted sub-title"><?php _l('configure-email-templates')?>
        </div>

    </div>
</div>

<div class="content-body">
    <form class="general-form " action="<?php echo getFullUrl(true)?>" method="post">

        <div class="row">


            <div class="col-md-6">
                <h6><?php _l('email-templates')?></h6>
                <div class="alert alert-dark" role="alert">
                    <?php _l('you-can-template-info')?>:<br/>
                    {full_name} - <?php _l('display-user-full-name-info')?>,<br/>
                    {email} - <?php _l('display-user-email-info')?>,<br/>
                </div>
                <hr/>
                <h6 class="colored"><?php _l('activation-email')?></h6>
                <hr/>
                <div class="form-group">
                    <label><?php _l('subject')?></label>
                    <div>
                        <input type="text"  name="val[activation-subject]" class="form-control"  value="<?php echo config('activation-subject')?>">
                    </div>
                </div>
                <div class="form-group">
                    <label><?php _l('content')?></label>
                    <textarea class="form-control" rows="5" name="val[activation-content]"><?php echo config('activation-content', '')?></textarea>
                </div>
                <hr/>
                <h6 class="colored"><?php _l('reset-password-email')?></h6>
                <hr/>
                <div class="form-group">
                    <label><?php _l('subject')?></label>
                    <div>
                        <input type="text"  name="val[reset-subject]" class="form-control"  value="<?php echo config('reset-subject')?>">
                    </div>
                </div>
                <div class="form-group">
                    <label><?php _l('content')?></label>
                    <textarea class="form-control" rows="5" name="val[reset-content]"><?php echo config('reset-content', '')?></textarea>
                </div>
                <hr/>
                <h6 class="colored"><?php _l('welcome-email')?></h6>
                <hr/>
                <div class="form-group">
                    <label><?php _l('subject')?></label>
                    <div>
                        <input type="text"  name="val[welcome-subject]" class="form-control"  value="<?php echo config('welcome-subject', '')?>">
                    </div>
                </div>
                <div class="form-group">
                    <label><?php _l('content')?></label>
                    <textarea class="form-control" rows="5" name="val[welcome-content]"><?php echo config('welcome-content')?></textarea>
                </div>

                <?php echo Hook::getInstance()->fire('admin.settings.email.template')?>
            </div>
        </div>




        <div class="floating-button">
            <button class="btn btn-float btn-primary"><i class="las la-check"></i></button>
        </div>
    </form>
</div>